### ISSUE TITLE
More options for generating the Rojo source map

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#10]
As mentioned in the README:

> Note that currently the language server only supports generating a sourcemap from a default.project.json. If other project files are necessary, please open an issue.

A few Wally packages that I work on need to have two separate Rojo project files:

**`default.project.json`**
```json
{
    "name": "package",
    "tree": {
    	"$path": "src"
    }
}
```

**`dev.project.json`**
```json
{
	"name": "package",
	"tree": {
		"$className": "DataModel",
		"ReplicatedStorage": {
			"Packages": {
				"$path": "Packages",
				"Package": {
					"$path": "src"
				}
			}
		}
	}
}
```

The file `default.project.json` is the file that will get published to Wally, while `dev.project.json` is used during development to have proper autocomplete/types/etc. It would be awesome if this was supported.

I thought I would also mention the `--include-non-scripts` flag for `rojo sourcemap`, including that flag makes for a substantially longer sourcemap creation time in a fully managed Rojo project that includes a 5-digit number of non-script instances. If that could also be made into an option so that it can be turned off, it would make file additions/deletions feel more responsive when using the LSP for projects such as these. Keeping it on by default still probably makes sense.

**Comment by JohnnyMorganz** [comment]
Whoops, didn't consider the size of `--include-non-scripts`. Yeah, should probably make it optional.

Should probably add in an option to toggle autogenerating sourcemaps on/off as a whole as well. Still listen for `sourcemap.json` changes, but in case the regeneration built-in doesn't yet suit a particular use case.
