### ISSUE TITLE
Shorter assertions for `require`

### ISSUE THREAD

**Issue by Qualadore** [JohnnyMorganz/luau-lsp#100]
To shorten my imports, a nice-to-have might be to take advantage of the fact that `assert()` returns the asserted value if it doesn't error.

This might be out of scope for Luau-LSP.

```lua
local replicated_storage: ReplicatedStorage = game:GetService("ReplicatedStorage")

local folder = assert(replicated_storage:FindFirstChild("folder"), "")
local module_script = assert(folder:FindFirstChild("module"), "")
local _module = require(assert(module_script:IsA("ModuleScript") and module_script, "")) -- This currently errors with `TypeError: Unknown require: unsupported path`.
```
(I recognize that asserting that the object is a `ModuleScript` is not necessary.)

This is what I do currently. The difference adds up once there are several imports, some a few levels deep.
```lua
local replicated_storage: ReplicatedStorage = game:GetService("ReplicatedStorage")

local folder = replicated_storage:FindFirstChild("folder")
assert(folder, "")
local module_script = folder:FindFirstChild("module")
assert(module_script, "")
assert(module_script:IsA("ModuleScript", "")
local _module = require(module_script)
```

**Comment by JohnnyMorganz** [comment]
I think the best we can probably handle is
```lua
local module = require(assert(folder:FindFirstChild("module")))
```
but the `assert(modulescript:IsA("ModuleScript") and module_script)` call is more challenging as that requires actual evaluation of the code. This should all be running statically

**Comment by JohnnyMorganz** [comment]
Turns out this is slightly more difficult than expected.
Require tracing is done internally by Luau: https://github.com/Roblox/luau/blob/master/Analysis/src/RequireTracer.cpp

It doesn't pick up the expression inside of `assert` so doesn't correctly trace the require

**Comment by JohnnyMorganz** [comment]
Unfortunately, I am going to close this for now as I don't think its something we can do currently.

It might turn out though that your assertions aren't actually necessary? If you are trying to please the diagnostics, using `game:GetService()` will resolve to any - you won't get any typing issues here, and you should still get good autocompletion
