### ISSUE TITLE
Some types are `any` in definitions depending on ordering

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#102]
WorldRoot.Raycast should return `RaycastResult?` as documented here:
<https://create.roblox.com/docs/reference/engine/classes/WorldRoot#Raycast>
But luau-lsp shows the return type as just `RaycastResult`
![image](https://user-images.githubusercontent.com/68730440/184802802-9e4e5c03-33ee-4972-a7fb-04cb6020cdb6.png)

RaycastParams.FilterDescendantsInstances should be typed as `{Instance}` instead of `{any}`.
![image](https://user-images.githubusercontent.com/68730440/184803804-62a46239-e508-47a5-8cab-1df6b3aa7265.png)

OverlapParams does not have property `IgnoreWater` as documented here:
<https://create.roblox.com/docs/reference/engine/classes/WorldRoot#Raycast>
But luau-lsp suggests and accepts `OverlapParams.IgnoreWater`
![image](https://user-images.githubusercontent.com/68730440/184806458-132294c4-270a-4d02-ac35-cda8e3b27ed8.png)

The types for `CFrame.Position` and `CFrame.p` are also wrong. They should be `Vector3`.
![image](https://user-images.githubusercontent.com/68730440/184802669-f1aa19f4-2e9b-45f7-b056-3c2a8d11d199.png)
![image](https://user-images.githubusercontent.com/68730440/184802689-20e851b4-ca03-4a91-982f-02c61dc9ccb4.png)

**Comment by JohnnyMorganz** [comment]
All the ones which resolve to `any` are incorrectly typed due to a Luau bug: https://github.com/Roblox/luau/issues/631

`IgnoreWater` is included in `OverlapParams` because its specified in the API dump. Strange that its not documented.

The result of Raycast can be fixed though

**Comment by ArchLand64** [comment]
Attempting to index `OverlapParams` with `IgnoreWater` will result in a runtime error. Therefore you should remove it from autocomplete.

![image](https://user-images.githubusercontent.com/68730440/185061958-a5183b1f-cf72-487b-9d6f-58b9983d2390.png)
![image](https://user-images.githubusercontent.com/68730440/185062043-05b26f3a-e5d7-408a-9b84-c9eff2493c30.png)

**Comment by JohnnyMorganz** [comment]
OverlapParams will be fixed in https://github.com/NightrainsRbx/RobloxLsp/pull/181

**Comment by JohnnyMorganz** [comment]
This has been fixed upstream which has been pulled in https://github.com/JohnnyMorganz/luau-lsp/commit/cd24f390b8c7d1f72f83d73ff788148d46ba076b
