### ISSUE TITLE
Exported package types sometimes do not work

### ISSUE THREAD

**Issue by nickthebob** [JohnnyMorganz/luau-lsp#107]
When running **wally-package-types --sourcemap sourcemap.json Packages/**, there's a possibility that exported package types are not read properly, showing **error-type** on Luau-LSP. From testing, wally packages like Sift have proper intellisense, while the **Net** package does not. 

This happens on **v1.9.0.** Older versions seem to work fine.

**Comment by JohnnyMorganz** [comment]
For net, setting `LuauTypeInferIterationLimit` FFlag to 0 resolves this issue.

There seems to be something hitting a limit internally in Luau

**Comment by JohnnyMorganz** [comment]
Going to fold this into #112 as a duplicate
