### ISSUE TITLE
`self` shown in parameter inlay hints incorrectly

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#110]
`self` is the incorrect parameter name for `workspace.Changed:Connect()`'s first explicit parameter.

![image](https://user-images.githubusercontent.com/68730440/185711062-1ddade07-c77b-4d16-9595-9b92c11f07ef.png)

![image](https://user-images.githubusercontent.com/68730440/185710755-7527bbb1-10fb-4f90-9651-6ebc8d6afcfe.png)

**Comment by JohnnyMorganz** [comment]
Can you enable the `LuauSelfCallAutocompleteFix3` FFlag and try again?
Or alternatively, disable FFlag syncing with Studio and have all flags enabled by default

**Comment by ArchLand64** [comment]
1) With FFlag syncing with studio disabled and all flags enabled by default, this issue still occurs.
2) With LuauSelfCallAutocompleteFix3 enabled, this issue still occurs.
![image](https://user-images.githubusercontent.com/68730440/185713039-c7001aa7-a6a1-4d42-b1b4-df5c7bca51f2.png)

**Comment by JohnnyMorganz** [comment]
Ah, it is because this is a `RBXScriptSignal`, which is currently typed as 
```lua
export type RBXScriptSignal<T... = ...any> = {
    Wait: (self: RBXScriptSignal<T...>) -> T...,
    Connect: (self: RBXScriptSignal<T...>, callback: (T...) -> ()) -> RBXScriptConnection,
    ConnectParallel: (self: RBXScriptSignal<T...>, callback: (T...) -> ()) -> RBXScriptConnection,
}
```
and Luau doesn't correctly specify `hasSelf`. This is blocked on https://github.com/Roblox/luau/issues/551
