### ISSUE TITLE
Improved rename support

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#117]
A few examples of where renaming can be improved:

```lua
-- Renaming both "tab" and "key" in any of these locations
local tab = {
	key = "foo",
}

tab.key = "bar"
```

```lua
-- Renaming "foo" or "bar" in any of these
local foo = 1

local function bar()
	foo = 2
end
```

It would also be cool to be able to rename types!

**Comment by JohnnyMorganz** [comment]
I am able to rename `tab`, `foo` and `bar` in these examples - are you not able to do so?

`tab.key` is the only one I can't do, but thats because we need to handle cross-file references (if tab was returned in a module) which we can't do yet

**Comment by filiptibell** [comment]
> I am able to rename `tab`, `foo` and `bar` in these examples - are you not able to do so?

Whenever I try to rename anything in the example I get this error:

```
[Error - 11:23:51 PM] Request textDocument/rename failed.
  Message: Rename is currently only supported for local variable bindings in the current file
  Code: -32803
```

This is with a completely blank file and pasting in the examples, so in that case I'm guessing this is a bug?

**Comment by JohnnyMorganz** [comment]
I also pasted in the examples in a blank file and it work for me... If you find a repro that would be awesome

**Comment by LastTalon** [comment]
I encounter this frequently as well and am also unsure how to reproduce this. Has there been any progress/leads that I may be able to help out with?

**Comment by filiptibell** [comment]
Seems like the abovementioned issue with flaky renaming is no longer happening for me, not sure when it got fixed but I am now able to rename 100% of the time 🚀

@LastTalon does the flaky renaming still happen for you?

**Comment by JohnnyMorganz** [comment]
Hah, forgot about this. It might've been because of https://github.com/JohnnyMorganz/luau-lsp/commit/7caf060043ebfed663d3f78fc8056a39c57aa491

**Comment by LastTalon** [comment]
Yeah, I haven't noticed it happening recently.
