### ISSUE TITLE
Instances cannot be compared with nil or instances of different classes

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#12]
The following code:

```lua
local m = Instance.new("Model")
if m.PrimaryPart == nil then
	print("Oh no")
end
```

Produces the following error at `m.PrimaryPart`:

`TypeError`
`Types BasePart and nil cannot be compared with == because they do not have the same metatable`
`Luau(1017)`

This might be because PrimaryPart is typed as `BasePart` and not `BasePart?` as in studio

The following code also produces the same error but for a seemingly different reason:

```lua
local m = Instance.new("Model")
if m == workspace then
	print("Oh no")
end
```

**Comment by JohnnyMorganz** [comment]
Partially resolved by https://github.com/JohnnyMorganz/luau-analyze-rojo/commit/2be9b45b3380eab1187f7dd8056fdfabaa4b23f8
