### ISSUE TITLE
Singleton types do not autocomplete when defining table keys

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#120]
When I define keys for tables defined as singleton types, autocomplete does not show up.
![Code_AViwQy7tj5](https://user-images.githubusercontent.com/68730440/188304342-d71c3899-996e-495e-bf2d-d4a4786fca3d.png)
![Code_O51q8BKZLP](https://user-images.githubusercontent.com/68730440/188304343-b2f8ce26-2c2e-443f-9d2c-e83d7fd6bae6.png)

Singleton type key autocomplete should look like the image below.
![Code_Ay7Yhg42kB](https://user-images.githubusercontent.com/68730440/188304349-fc109690-1d08-4139-b52d-afa445bef36f.png)

**Comment by JohnnyMorganz** [comment]
We rely on Luau to provide Autocomplete info. I would double check if this is also an issue in Studio, and if so, transfer this to the Luau repo

**Comment by ArchLand64** [comment]
Roblox Studio also has this issue, so I will close this issue and copy it to the Luau repo.
