### ISSUE TITLE
Incorrect DataStoreService method return types

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#129]
Luau-lsp says all 4 of the DataStoreService methods return `any`, and this is incorrect. 
They should return the types documented here: https://create.roblox.com/docs/reference/engine/classes/DataStoreService#summary-methods

```lua
local DataStoreService = game:GetService("DataStoreService")
DataStoreService:GetDataStore() --should return GlobalDataStore
DataStoreService:GetGlobalDataStore() --should return GlobalDataStore
DataStoreService:GetOrderedDataStore() --should return OrderedDataStore
DataStoreService:ListDataStoresAsync() --should return DataStoreListingPages
```

**Comment by JohnnyMorganz** [comment]
This is the same problem as #102, so I am going to close it as a duplicate
