### ISSUE TITLE
Add option to customize enabled FFlags

### ISSUE THREAD

**Issue by ayuka** [JohnnyMorganz/luau-lsp#13]
Blindly enabling all FFlags can result in unintended Luau errors that aren't reproducible in Roblox Studio. Is there possibly a way to match the currently enabled flags for Roblox, and also provide customization (e.g. toggling a specific flag)?

**Comment by JohnnyMorganz** [comment]
I agree, we should add a way to customise FFlags here

For matching the currently enabled flags, this endpoint may be helpful: https://clientsettingscdn.roblox.com/v1/settings/application?applicationName=PCDesktopClient

**Comment by Corecii** [comment]
I need this to raise the limits of the typechecker [like I did for luau-analyze-rojo](https://github.com/JohnnyMorganz/luau-analyze-rojo/pull/23). Until then I can't use this LSP!

I'd have a look at doing this myself, but I think you're already on it, right?
