### ISSUE TITLE
Required modules' types do not update

### ISSUE THREAD

**Issue by nezuo** [JohnnyMorganz/luau-lsp#14]
If you require a module that returns a function, for example, and change the return to a table, other scripts that require that module will still have the old function type. The script that is requiring the module has to be open while the module gets updated for this to happen.

Closing the module and/or the script that requires it does not fix the issue.

How to reproduce:
1. `rojo init`
2. Paste following code into `src/server/init.server.lua`:
```lua
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Hello = require(ReplicatedStorage.Common.Hello)

Hello()
```
3. Keep the server script open
4. Paste following code into `src/shared/Hello.lua`:
```lua
return {
	hello = function() end,
}
```
5. Change the last line in `src/server/init.server.lua`: `Hello.hello()`
6. Error appears on that line: `TypeError: Type '() -> ()' does not have key 'hello'`

**Comment by JohnnyMorganz** [comment]
The issue seems to be an internal mismatch between real file paths and virtual file paths
![image](https://user-images.githubusercontent.com/19635171/171955527-09d0b41b-0bbb-433e-b733-03633536f00a.png)

We need to fix this by probably using virtual file paths for all sources
