### ISSUE TITLE
Issues with `Player` type

### ISSUE THREAD

**Issue by lopi-py** [JohnnyMorganz/luau-lsp#146]
Hey I got issues when using `Player` type
![image](https://user-images.githubusercontent.com/70210066/191159323-6b42c21b-bca0-4acf-8ec5-8f36c8a791fe.png)
note that if I use any other type it works
![image](https://user-images.githubusercontent.com/70210066/191159665-0ca352a1-d11c-4052-a19b-151825080dc7.png)

Type definition
![image](https://user-images.githubusercontent.com/70210066/191159505-6c087287-010a-4bc8-8a24-d1344a653388.png)

**Comment by JohnnyMorganz** [comment]
This looks related to https://github.com/JohnnyMorganz/luau-lsp/issues/112

Could you try setting the FFlag `LuauTarjanChildLimit` to 0 and seeing if it still errors?

**Comment by lopi-py** [comment]
Ahh thanks, yes it fixes
