### ISSUE TITLE
Issue with OOP paradigm

### ISSUE THREAD

**Issue by lopi-py** [JohnnyMorganz/luau-lsp#147]
Ok I know that this isn't a 100% true way to oop but this its actually way. I got this error when using `--!strict`, when I remove it, doesn't throw the error
![image](https://user-images.githubusercontent.com/70210066/191160147-04cdb6a5-e62e-47af-bf18-9b3787f96328.png)
but this error seems very weird:
![image](https://user-images.githubusercontent.com/70210066/191160550-4b18bc6c-0764-4f6a-82ee-84ef27520828.png)
![image](https://user-images.githubusercontent.com/70210066/191160500-88c5df5c-387e-4f75-8309-0a3b9b7ab789.png)

**Comment by JohnnyMorganz** [comment]
There isn't much Luau LSP can do here. This is a Luau issue.
Make sure your `Entity` type encompasses everything.
I would recommend trying one of the examples in https://github.com/Roblox/luau/pull/578 to see if it helps

**Comment by lopi-py** [comment]
I tried examples and works as expected, thanks
