### ISSUE TITLE
Type errors are printed twice by `luau-lsp analyze`

### ISSUE THREAD

**Issue by zeux** [JohnnyMorganz/luau-lsp#149]
```
$ cat oof.lua
local x: table = {}

$ ~/luau-lsp analyze oof.lua
oof.lua(1,10): TypeError: Unknown type 'table'
oof.lua(1,10): TypeError: Unknown type 'table'
oof.lua(1,7): LocalUnused: Variable 'x' is never used; prefix with '_' to silence
```

This isn't a problem with luau-analyze, so it doesn't seem to be a bug on Luau side.

**Comment by JohnnyMorganz** [comment]
Looks like something wasn't copied over correctly

luau-lsp:
https://github.com/JohnnyMorganz/luau-lsp/blob/dd3c61233c3485e3eeb3c995e17855fcf6f5b195/src/AnalyzeCli.cpp#L52-L62

Luau analyze:
https://github.com/Roblox/luau/blob/59fd9de48598724c7e44bb455bff9e5f5a7df0f0/CLI/Analyze.cpp#L52-L63
