### ISSUE TITLE
Missing children

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#16]
When indexing a player, IntelliSense is missing `Player.PlayerGui` along with some other instances listed below.
- Children of StarterGui -> Player.PlayerGui
- Children of StarterPack -> Player.Backpack
- Children of StarterPlayerScripts -> Player.PlayerScripts
- StarterPlayer.StarterCharacter -> Player.Character

The current workaround for this bug is to manually add these instances into your project.json file.

**Comment by JohnnyMorganz** [comment]
Hm, from a "correctness" perspective, should we automagically be inferring that the children of the relevant StarterXXX are present in the player's version?
I can't remember if it is a requirement to use WFC instead

We should definitely be adding the containers as children though

**Comment by ArchLand64** [comment]
The children of StarterXXX are not guaranteed to be present in the player's corresponding instances, but I think it would be inconvenient to make users always WFC. Roblox Studio also assumes that the children are always present.

![image](https://user-images.githubusercontent.com/68730440/171953808-e4c8e3d8-1a82-4a57-b677-1dcb5a472c17.png)

I know a couple of developers including myself that have this pattern in their screengui related init scripts:
```lua
local myScreens = game.Players.LocalPlayer.PlayerGui
for _, screenObj in ipairs(game.StarterGui:GetChildren()) do
    myScreens:WaitForChild(screenObj.Name)
end
--all other screengui related code after this line can safely assume the player's screenguis are present
startScreenGuiModules()
```

I think requiring to use WFC in this case could be an extension option for a "super strict" mode that would also cause other functions like FindFirstChild to return `Instance?`.

**Comment by nezuo** [comment]
All descendants of `StarterPlayer` are guaranteed to exist after `game:IsLoaded()` returns true. `LocalScript`s that a run inside of `ReplicatedFirst` are run before `game.Loaded` fires while `LocalScript`s in other locations like `PlayerScripts` are run after it is fired. This means that `WaitForChild` is only necessary in certain situations. You would have to detect where a script runs to know whether you need to use `WaitForChild`.

**Comment by JohnnyMorganz** [comment]
> The children of StarterXXX are not guaranteed to be present in the player's corresponding instances, but I think it would be inconvenient to make users always WFC. Roblox Studio also assumes that the children are always present.

Thanks for testing this in Studio! I think its reasonable to mimic studio in this case
