### ISSUE TITLE
Doesn't detect types defined below if there's a syntax error

### ISSUE THREAD

**Issue by fewkz** [JohnnyMorganz/luau-lsp#160]
When there's a syntax error, luau-lsp isn't able to detect types defined at the same scope level

![image](https://user-images.githubusercontent.com/83943819/192212456-f8a81d42-cd5e-4da1-97ad-bda730bd33d3.png)

It would be able to recognize `Bar` if there wasn't a syntax error

**Comment by JohnnyMorganz** [comment]
Parsing is handled by Luau. I would recommend moving this to the Luau repo (maybe check if the same issue also occurs in Studio)
