### ISSUE TITLE
Complains if you have a non-rojo folder in a workspace

### ISSUE THREAD

**Issue by fewkz** [JohnnyMorganz/luau-lsp#164]
Luau-lsp tries to generate a sourcemap for the server folder even though it's not a rojo project and gives a warning.

![Code_2022-09-27_03-04-55](https://user-images.githubusercontent.com/83943819/192456954-5ab8bf55-fb17-4c5d-ac99-5d3f7dcedc43.png)

![Code_2022-09-27_03-04-47](https://user-images.githubusercontent.com/83943819/192456959-3833211e-ce7c-4b63-a9fb-633f794efe6d.png)

My workspace configuration looks like this
```json
{
    "folders": [
        {
            "path": "plugin"
        },
        {
            "path": "server"
        }
    ],
    "settings": {}
}
```

**Comment by JohnnyMorganz** [comment]
You should configure a `.vscode/settings.json` in the `server` folder and disable sourcemap support

**Comment by fewkz** [comment]
> You should configure a `.vscode/settings.json` in the `server` folder and disable sourcemap support

I just tried that, but it doesn't look like the extension supports settings for folders

**Comment by JohnnyMorganz** [comment]
https://github.com/JohnnyMorganz/luau-lsp/commit/3eae5af00449f15e915bf72abb1e624f6bf29221 adds support for folders
