### ISSUE TITLE
FindFirstAncestor does not properly resolve children

### ISSUE THREAD

**Issue by vocksel** [JohnnyMorganz/luau-lsp#18]
I have the following project:

```json
{
  "name": "flipbook",
  "tree": {
    "Packages": {
      "$path": "Packages"
    },
    "$path": "src"
  }
}
```

And in a module under `src/` I am trying to include the following:

```
local flipbook = script:FindFirstAncestor("flipbook")
```

The `flipbook` variable is typed as `Instance`, which tells me that luau-lsp is at least doing some work, but attempting to index `flipbook` for any of its child modules comes up empty.

I'm unsure if this is a misconfiguration on my part, or if luau-lsp just doesn't support this yet

For further context, you can view the source code for the repo [here](https://github.com/vocksel/flipbook/)

**Comment by JohnnyMorganz** [comment]
This is not yet supported, but is definitely something we should do
