### ISSUE TITLE
"Request ... failed."

### ISSUE THREAD

**Issue by cyrus01337** [JohnnyMorganz/luau-lsp#190]
### Summary
Popups saying either `"Request textDocument/hover failed."` or `"Request textDocument/inlayHint failed."` are being spammed while I'm scrolling through my scripts when there is an error in my code as shown before. Currently under the assumption that I am meant to be notified of something or that the popup, er, popping up was a mistake.

![image](https://user-images.githubusercontent.com/63274991/195961780-4ecc5782-3456-4c14-a79e-3df2d646d338.png)

### Specifications
OS: Windows 10
Editor: VS Code
Extension Version: v1.11.2

**Comment by JohnnyMorganz** [comment]
Yeah this is a known issue which I can't reproduce right now. If you find reproduction steps that would be incredibly useful.

I've added a little bit more logging in the nightly release

**Comment by JohnnyMorganz** [comment]
I've pushed a fix as https://github.com/JohnnyMorganz/luau-lsp/commit/83e4f467bc97368f50b538903796da753121ab94, lets see if that helps

**Comment by cyrus01337** [comment]
Sorry for the late feedback, this seems to have resolved the issue. It may resurface during split pane which was something I forgot to mention, but this has not been reproducible since the fix so I am going to assume this was fixed.

Thanks as always for the hard work! 👍
