### ISSUE TITLE
Option to hide metatable special keys from autocomplete

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#196]
Some members of tables show up in autocomplete even though they are not really useful, take this basic OOP example:

```lua
local class = {}
class.__index = class

function class.new()
	return setmetatable({}, class)
end

local object = class.new()

-- Autocomplete shows __index here
object.
```

So, given this example, it seems it would be useful to be able to hide known metatable special keys. Maybe this could even be extended to hide any property that begins with an underscore, since that is a common way to denote private members.

**Comment by JohnnyMorganz** [comment]
Would it be sufficient to just deprioritise it instead of hiding it completely? I imagine it *may* be useful in some cases (but I don't really know when)

**Comment by filiptibell** [comment]
> Would it be sufficient to just deprioritise it instead of hiding it completely? I imagine it _may_ be useful in some cases (but I don't really know when)

Deprioritising it is probably a good idea in general, yeah. I have personally not found the autocomplete to be useful since its usually more of a class implementation detail and not relevant in user-facing/business logic type code, but either solution works.
