### ISSUE TITLE
Incorrect parameter is highlighted

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#207]
![image](https://user-images.githubusercontent.com/68730440/196888277-9ec1eede-de35-4a9d-9506-1b21f83bd4d8.png)
![image](https://user-images.githubusercontent.com/68730440/196888289-0725cab6-d7ba-4c50-90d2-185b65a0fe0a.png)

I want the highlighted parameter to be based on the position of my text cursor, as demonstrated by Roblox-lsp.

**Comment by LastTalon** [comment]
It looks like this may be using snippets for some reason. It probably shouldn't. Until you complete the snippet it appears to be in the first position.
