### ISSUE TITLE
Requiring player module results in unknown require error.

### ISSUE THREAD

**Issue by Lyzrinn** [JohnnyMorganz/luau-lsp#208]
![image](https://user-images.githubusercontent.com/45791865/197030367-f01ca947-f6d0-4ca4-b79b-d51071771a52.png)

As you can see, trying to require the PlayerModule results in error 1011 unknown require. 
Luau LSP probably only checks for module that can be found in the current hierarchy and not during runtime.

Not sure if I'm doing something wrong on my end, usually when this happens I restart VSCode and it fixes most issues, but this one it doesn't.

**Comment by JohnnyMorganz** [comment]
Yeah, there isn't much we can do about this, as the module only gets injected at runtime, so we can't require it.
You can silence the error using `require(PlayerModuleScript) :: any`

**Comment by Lyzrinn** [comment]
> Yeah, there isn't much we can do about this, as the module only gets injected at runtime, so we can't statically require and analyze it. You can silence the error using `require(PlayerModuleScript) :: any`

Thank you, that's a perfect solution !

**Comment by Lyzrinn** [comment]
Just another little detail that has no importance in our use-case, the path to the module in the error is wrong. 
It mentions game/StarterPlayer although i'm requiring the module from the PlayerScripts inside the player instance.

It works in studio, and silencing the error just works, but you might want to keep that in mind in case someone has a similar wrong path error.
