### ISSUE TITLE
Use ClassName for instance type name

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#21]
I generated a single rbxm for workspace using remodel, then I added it to my project json file like this:
```json
    "Workspace": {
      "$path": "src/Workspace.rbxm"
    }
```

When I hover over the variable, I expect to see its type as `BasePart`. Instead it just shows the name of the instance.
![image](https://user-images.githubusercontent.com/68730440/172065795-821f13e4-bd65-43ff-aa94-340e6bc4d458.png)

**Comment by JohnnyMorganz** [comment]
This is on purpose, it makes the type the same as the instance name, the underlying type is a BasePart though.

Do you think it would make more sense to use the class name as the type instead? How does Studio show the type

**Comment by ArchLand64** [comment]
It does not look like the underlying types are the same. I also get type errors when I try to swap BaseParts between variables.
![image](https://user-images.githubusercontent.com/68730440/172066347-57d5d80b-fed7-4d7a-87fd-0083262d4e97.png)

Roblox Studio shows the variable's type as its class name. 
![image](https://user-images.githubusercontent.com/68730440/172066224-33b4b631-0dbf-4b33-93a8-1cff28c1df12.png)

**Comment by JohnnyMorganz** [comment]
The type error when swapping seems to be related to #12 
Even if we changed the name, that error would probably still be there, not entirely sure what's causing it yet.

I think I probably will change the name to the class name though, it makes it better to reason about (and you can already see the name in the script!)
