### ISSUE TITLE
Improved behavior for completion to inside of function call parentheses

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#211]
1. Type something such as `workspace.ChildAdded:Conn|` where the bar is the cursor
2. Accept the completion, text is now `workspace.ChildAdded:Connect(|)`
3. Make an anonymous function and move cursor onto the second line of this:
```lua
workspace.ChildAdded:Connect(function()
|
end)
```
4. Press tab expecting it to indent, but snippet forces the cursor to after the parens

It would be preferrable for me personally to have the snippet only move into the parens initially and not have the two different stops since the second one would move me out of the function. Should probably be a setting for people who want that behavior.

**Comment by JohnnyMorganz** [comment]
Added to options to support this:
`luau-lsp.completion.addParentheses`: configure whether we should add parentheses when completing a function call
`luau-lsp.completion.addTabstopAfterParentheses`: configure whether a tabstop is included after the parentheses, which allows you to press `tab` once completed to move out of parentheses. Requires `addParentheses`
