### ISSUE TITLE
Enum can't be indexed as a table

### ISSUE THREAD

**Issue by TheHackerPuppy** [JohnnyMorganz/luau-lsp#212]
**Problem**
 I can't index Enum like this:
 ```lua
Enum["UserInputType"]["Keyboard"]
```

**Error**
TypeError: Expected type table, got 't1 where t1 = {| AccessoryType: Enum.AccessoryType, ActionType: Enum.ActionType, ActuatorRelativeTo: Enum.ActuatorRelativeTo, ActuatorType: Enum.ActuatorType, AdPortalStatus: Enum.AdPortalStatus, AdPortalType: Enum.AdPortalType, AdShape: Enum.AdShape, AdornCullingMode: Enum.AdornCullingMode, AlignType: Enum.AlignType, AlphaMode: Enum.AlphaMode, AnalyticsEconomyAction: Enum.AnalyticsEconomyAction, AnalyticsLogLevel: Enum.AnalyticsLogLevel, AnalyticsProgressionStatus: Enum.AnalyticsProgressionStatus, AnimationPriority... *TRUNCATED*' instead

**Comment by JohnnyMorganz** [comment]
This is a Luau bug: https://github.com/Roblox/luau/issues/533#issuecomment-1291779353

We changed the type of `Enum` to
```
type Enum = {
     AccessoryType: Enum.AccessoryType,
     ActionType: Enum.ActionType,
     ....
} & { GetEnumItems: () -> { Enums } }
```
which looks like you can no longer index it via a string

**Comment by TheHackerPuppy** [comment]
Oh, is this going to be fixed? Or how can I index now an unknown property?

**Comment by TheHackerPuppy** [comment]
ok, thank you very much for your help

**Comment by JohnnyMorganz** [comment]
Will close this as there isn't much we can do, you can track the Luau issues instead
