### ISSUE TITLE
Preview `BrickColor` and `Color3` colors

### ISSUE THREAD

**Issue by Qualadore** [JohnnyMorganz/luau-lsp#217]
![RobloxStudioBeta_sCHYBLfPtG](https://user-images.githubusercontent.com/93345551/198741585-06446ac5-7ccc-43d0-b3d2-c0f6af4e377b.png)
I'm not sure if this in scope, but it might be a nice quality of life change.

**Comment by JohnnyMorganz** [comment]
Yeah, would be neat, but also not sure if it fits within the project. Should be pretty simple to add though

**Comment by bubshayz** [comment]
> Yeah, would be neat, but also not sure if it fits within the project. Should be pretty simple to add though

It really can be considered as an additional 'good-to-haves' feature for an LSP. Feature like this would also improve my workflow too since I won't be required to constantly switch between Studio and VSC just for colors..
