### ISSUE TITLE
Types not being exported from modules along a FindFirstAncestor path

### ISSUE THREAD

**Issue by vocksel** [JohnnyMorganz/luau-lsp#22]
I have a `types.lua` file at the root of my project that simply exports types and returns an empty table.

The following using a relative path works just fine:

```lua
local types = require(script.Parent.Parent.Parent.types)

export type Node = {
	name: string,
	children: { Node },
	icon: string?,
	instance: Instance?,
	storybook: types.Storybook,
}
```

However, the following does not work for types:
```lua
local flipbook = script:FindFirstAncestor("flipbook")
local types = require(flipbook.types)

export type Node = {
	name: string,
	children: { Node },
	icon: string?,
	instance: Instance?,
	storybook: types.Storybook, -- <-- This is highlighted as an error
}
```

Note that FindFirstAncestor paths _do_ work for non-type members. Seems to be just types that aren't getting picked up

**Comment by JohnnyMorganz** [comment]
If you apply strict mode, I assume you get an unknown require error? What path does the unknown require error give
