### ISSUE TITLE
Adding the extension to Open VSX Registry

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [JohnnyMorganz/luau-lsp#226]
Right now, the extension is only available on the Microsoft's VSCode extension marketplace, this makes the extension inaccessible to users using a different version of VSCode such as [``code-server``](https://github.com/coder/code-server) or [``VSCodium``](https://github.com/VSCodium/vscodium). Right now the only workaround I could find was to download the extension package and then installing them manually.

Perhaps add the extension to the [``Open VSX Registry``](https://open-vsx.org)?

**Comment by JohnnyMorganz** [comment]
Does OpenVSX support platform specific extensions? We upload different vsix for Windows Mac and Linux (and then also x64 vs arm)

If that's supported, then happy to upload them to the registry

**Comment by RealEthanPlayzDev** [comment]
@JohnnyMorganz I'm not sure unfortunately, I never made VSCode extensions nor have once published them, but maybe it does? Roblox LSP is there as far as I know.

**Comment by JohnnyMorganz** [comment]
I've published the extension at https://open-vsx.org/extension/JohnnyMorganz/luau-lsp

I slightly messed it up, right now just the Windows extension is published and its acting as a universal extension.

Future releases should do this properly and publish for macos/linux correctly

**Comment by RealEthanPlayzDev** [comment]
Alright, I'll close this issue, thanks @JohnnyMorganz !
