### ISSUE TITLE
Instance.GetChildren returns "Objects"

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#23]
Instead of returning an array of Instances, luau-lsp says `workspace:GetChildren()` returns `Objects`. This happens for any other instance as well.
![image](https://user-images.githubusercontent.com/68730440/172530837-30d39991-84df-4091-a6f5-761011fb7ac2.png)

This is what Roblox Studio shows for workspace:GetChildren()
![image](https://user-images.githubusercontent.com/68730440/172531503-69777a99-7616-49aa-a055-107175cf1d82.png)

**Comment by ArchLand64** [comment]
It seems like this is a common mistyping when I search for "Objects" in 
`https://raw.githubusercontent.com/CloneTrooper1019/Roblox-Client-Tracker/roblox/API-Dump.json`

**Comment by JohnnyMorganz** [comment]
Object internally is just typed as `type Object = { Instance }`, so overall it shouldn't produce an issue except for a weird name

Does this lead to any errors? I have a fix anyway to resolve this, but wondering if it's a major concern

**Comment by ArchLand64** [comment]
This does not lead to any errors, but type inference seems thinks it returns an array of `any`. So autocomplete does not work here. This is not a major concern for me though, since typecasting can enable autocomplete to work again.
![image](https://user-images.githubusercontent.com/68730440/172676982-e0b03238-9b09-4a53-9b93-7a8713c38a93.png)

Roblox Studio will autocomplete for instance keys when indexing an array of instances.
![image](https://user-images.githubusercontent.com/68730440/172677681-e4eb54b9-ea3a-40e4-b56d-0bdeac6d24da.png)

**Comment by JohnnyMorganz** [comment]
That type inference thing is definitely strange - are you in strict mode with this?

**Comment by ArchLand64** [comment]
I think so, because in both screenshots I posted above I have `--!strict` at the top of my script. Here is my test code:
```lua
--!strict
--type inference says stuff is {any}
local stuff = workspace:GetChildren()
--autocomplete for stuff[1] won't work here
```
