### ISSUE TITLE
Support for more doc comment formats

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#236]
Right now function doc comments only support the following syntax:

```lua
--[=[
    Contents here
]=]
```

It would be nice if the LSP could also support plain multiline comment blocks with no equals sign, or optionally support for any variable number of matching equals signs like the language itself does.

**Comment by JohnnyMorganz** [comment]
The main reason this isn't done right now is to allow for general multiline comments which aren't necessarily documentation, so it doesn't show up in the doc section.

Making all multiline comments doc comments may be overly greedy, do you have specific cases where it would be helpful this is supported?

**Comment by filiptibell** [comment]
> Do you have specific cases where it would be helpful this is supported?

Most of the cases I've seen where it would be helpful are in older libraries & libraries that don't and probably never will use the `--[=[ ]=]` format, I'll link a couple of example files:

https://github.com/Roblox/roact/blob/master/src/createElement.lua
https://github.com/Roblox/rodux/blob/master/src/Store.lua
https://github.com/osyrisrblx/t/blob/master/lib/init.lua

I haven't looked at the specifics of parsing & implementation of doc comments in luau-lsp but I tend to find some other non-standard but symmetric formats from time to time as well, such as in the last linked file. Maybe there's some general solution for supporting that, too?

> The main reason this isn't done right now is to allow for general multiline comments which aren't necessarily documentation, so it doesn't show up in the doc section.

Looking through the above libraries and some others it seems that any time a multiline comment block is directly above a function they are documenting that specific function. I personally can't seem to find anywhere that this is not the case. Maybe a special case is needed here where comment blocks above functions are greedier than (future) comment blocks on variables, tables/modules etc.

**Comment by LastTalon** [comment]
This seems useful, but also seems like an inherently hard problem, since none of those examples are really following an agreed upon standard and the only attempt to set a standard has been with moonwave style comments.

This is the sort of reason that documentation comments have a particular format that sets them apart from standard comments. You don't really know how anyone is going to use comments in general.

In my personal work experience, I know of a lot of comments that this wouldn't work for. I know engineers that frequently comment code out with multi-line comments without regard for things like this, or use multi-line comments for typical code annotations that aren't meant to be documentation in the same way.

**Comment by filiptibell** [comment]
> In my personal work experience, I know of a lot of comments that this wouldn't work for. I know engineers that frequently comment code out with multi-line comments without regard for things like this, or use multi-line comments for typical code annotations that aren't meant to be documentation in the same way.

That's why I proposed comment blocks specifically above functions could be greedier than in other places in my above reply. Have you encountered multiline comment blocks directly attached to functions (so no blank lines between) that are not documenting the function itself? I've been trying to look through public lua repos but so far haven't found any cases of that.

**Comment by LastTalon** [comment]
That could be a way to address it. My concern is really just that I don't think the people doing it really have concern for whether that happens or not. I don't have any specific examples in mind though.

**Comment by JohnnyMorganz** [comment]
I'm going to support a variable number of `=` signs for now and see how it goes. If it becomes problematic, we can revert the change.
