### ISSUE TITLE
Cannot require PlayerScripts in local player

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/luau-lsp#24]
```
TypeError: Unknown require: game/Players/LocalPlayer/PlayerScripts/PurchaseClient
```

We should map `game/Players/LocalPlayer/PlayerScripts` to `StarterPlayerScripts` (and similar for StarterGear, StarterGui etc.)

**Comment by HawDevelopment** [comment]
Isn't this (kinda) a Rojo source map bug/qol?

**Comment by JohnnyMorganz** [comment]
No, I think we can look into the `context.name` when resolving modules, and convert `game/Players/LocalPlayer/X` to the `game/StarterX` there, and it will automatically require the module from that location.

Of course, we assume that all the StarterX scripts get copied to the their Player counterparts, and it is not deleted at runtime, but I think that's a reasonable assumption. We also can't handle something like `CmdrClient` where scripts are moved dynamically at run time, but there isn't much we can do there (to get type support you can do `require(LocalPlayer.PlayerScripts.CmdrClient) :: typeof(require(game.ReplicatedStorage.Cmdr.CmdrClient))`)
