### ISSUE TITLE
Doc comments do not attach to certain kinds of function declarations

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#247]
Functions declared like this do not get doc comments attached:

```lua
--[=[
	Doc comment
]=]
local func = function()

end
```

EDIT: I realized now that this may count as a doc comment on a variable and not on a function declaration, let me know if this is just that feature missing and not actually a bug.

**Comment by JohnnyMorganz** [comment]
Yep, its because its attached to a variable. We should be able to track this though
