### ISSUE TITLE
Incorrect type error for RaycastParams.RespectCanCollide

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#248]
Luau-lsp incorrectly says the following code is invalid: 
```lua
local castParams = RaycastParams.new()
castParams.RespectCanCollide = true
```
![image](https://user-images.githubusercontent.com/68730440/208050722-05fedc1b-9779-4f44-995f-49ed96c7d780.png)

But in Roblox Studio, this code works and its script analysis does not report any type errors.

**Comment by JohnnyMorganz** [comment]
Requires a patch in the data types provided by Roblox LSP. I've opened the following PR: https://github.com/NightrainsRbx/RobloxLsp/pull/199

**Comment by JohnnyMorganz** [comment]
Added in https://github.com/JohnnyMorganz/luau-lsp/pull/250
