### ISSUE TITLE
Ignored error returning error code 1.

### ISSUE THREAD

**Issue by ohimesan** [JohnnyMorganz/luau-lsp#249]
I may have found a bug on Luau LSP analyze... if you try to use --ignore on a file that throws an error, it will return the error code 1.
here is a mini repo with the problem, if you try to run `luau-lsp analyze --ignore=example.lua` it won't print nothing because it ignored the error - but an error code was returned.
![image](https://user-images.githubusercontent.com/59834219/208137072-b6966320-552f-4306-be20-a731fc58a155.png)

[luauerror.zip](https://github.com/JohnnyMorganz/luau-lsp/files/10247171/luauerror.zip)

**Comment by vocksel** [comment]
Experiencing this as well. Relevant [action run](https://github.com/vocksel/flipbook/actions/runs/3783613998/jobs/6432297365) and [workflow lines](https://github.com/vocksel/flipbook/actions/runs/3783613998/workflow#L33-L55)
