### ISSUE TITLE
Move sourcemap generation to server

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/luau-lsp#25]
Currently, sourcemaps are regenerated on the client and the server listens for watched file changes.

We should move this to the server by calling out to the rojo executable directly.

Advantages:
- More portable, as currently we rely on the client specifically adding in sourcemap regeneration, which is only supported in the VSCode extension
- We can create the sourcemap internally so that `sourcemap.json` is not created in the workspace unnecessarily

Disadvantages:
- Complexity, calling out to subprocesses

**Comment by JohnnyMorganz** [comment]
There is actually some positives to reading a `sourcemap.json` file in the workspace - it allows systems other than Rojo to be used, provided it generates a sourcemap in the same format.

For that reason, I'm going to leave this be and not move it to server only

**Comment by LastTalon** [comment]
Would it be possible for it to generate on the server and use the sourcemap in the working directory if one exists? I think the majority of the cases will be using rojo and don't need/expect this artifact of operation to show up in their working directory.

My experience working with people using this has typically been that they're usually unsure where this file has come from or what its doing there.
