### ISSUE TITLE
Doc comment support in type definitions

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#252]
```lua
export type Roact = {
	--[=[
		Creates a roact element.

		...
	]=]
	createElement: () -> (),
}
```

This could be a potential solution to older libraries not having moonwave-style doc comments. A user could then make a wrapper package that exports proper types and documentation comments pulled from the original package.

This is also a potential solution to classes that are difficult to add types to using the idiomatic `export class Class = typeof(Class.new())` and that need a full type definitions to work well.

Possibly related to #236 considering the above remarks

**Comment by JohnnyMorganz** [comment]
Copying from what I said on Discord:

The doc comments system works by finding all the associated comments closest to a specific position in a file.
There are two things missing right now:

1) We are unable to track locations of type aliases in the original file they were declared in. This needs to either be fixed upstream https://github.com/Roblox/luau/issues/598, or another solution found (e.g., lookup the Module and search through the scopes for the declaration)

2) Comments are currently attached only at the statement level. We need to be more granular here by attaching comments to specific properties in a table / type table

**Comment by JohnnyMorganz** [comment]
Currently blocked on https://github.com/Roblox/luau/issues/802
