### ISSUE TITLE
Luau-LSP Roblox Plugin Bug

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#254]
After connecting to Roblox Studio with the Luau-LSP plugin, instance type refinement starts to dysfunction. I do not experience this issue with Roblox Studio's script editor.
```lua
workspace.Terrain.ChildAdded:Connect(function(objAdded)
    if objAdded:IsA("BasePart") then
        objAdded.Transparency = 1
    end
end)
```
![image](https://user-images.githubusercontent.com/68730440/210770874-3275f97d-01b9-4685-adad-d519d7e31117.png)

**Comment by JohnnyMorganz** [comment]
This doesn't just affect the plugin instances but also affects instances declared in the sourcemap
