### ISSUE TITLE
Incorrect RunService type errors

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#261]
I am getting incorrect type errors for the following code: 
```lua
game:GetService("RunService").Stepped:Connect(function(currTime, deltaTime)
	local e1 = currTime + 1
	local e2 = deltaTime + 1
end)
```
![image](https://user-images.githubusercontent.com/68730440/211436309-5e08108d-659e-45f9-a39e-a2ec1089a2cd.png)

This problem affects the other RunService events and also happens in Roblox Studio.

**Comment by JohnnyMorganz** [comment]
This is related to https://github.com/JohnnyMorganz/luau-lsp/issues/83#issuecomment-1192865024

For the diagnostics type checker, `game` is typed as any, so this leads to `deltaTime` being typed as any, so it doesn't know the correct type annotation

**Comment by JohnnyMorganz** [comment]
Closing as there are no solution for now
