### ISSUE TITLE
A bad FVariable config will prevent the server from loading.

### ISSUE THREAD

**Issue by metatablecat** [JohnnyMorganz/luau-lsp#281]
So I've spent the last 10 minutes trying to figure out why the LSP wasn't starting, and it turns out there was somehow an FFlag with no assigned name or value, and I dont know how it got there?

It should probably be a good idea to ignore these "bad" fflags, if that's not possible, it could just warn to the user of the extension that there's bad flags in the config.

**Comment by JohnnyMorganz** [comment]
Can you explain further? What was your settings? We do already warn and ignore unknown FFlags

**Comment by metatablecat** [comment]
So, if you create an FFlag setting with the following config:
```json
"luau-lsp.fflags.override": {
	"": ""
}
```

The debug console will throw:
![image](https://user-images.githubusercontent.com/41757236/215951839-c72a2cb2-8223-4ae2-8428-279d6d3c5efb.png)

After this error has happened, the language server does not start, and the user is not informed of said failure
