### ISSUE TITLE
Feature request on `Failed to read definitions file`

### ISSUE THREAD

**Issue by dmi7ry** [JohnnyMorganz/luau-lsp#282]
It would be useful to see what exactly problem is instead of just `Failed to read definitions file`.
Could you add some details to the error message, please?

**Comment by JohnnyMorganz** [comment]
The LSP typically adds some diagnostics to the definitions file, if you open it up in your editor it should highlight the problems

**Comment by dmi7ry** [comment]
Ah, great. I didn't know it. Thank you.

**Comment by JohnnyMorganz** [comment]
Going to close this as completed for now, let me know if it should be improved
