### ISSUE TITLE
`.luaurc` not detected without specifying `--base-luaurc`

### ISSUE THREAD

**Issue by Qualadore** [JohnnyMorganz/luau-lsp#285]
I had a "failed to unify type packs" error that occurred when using `luau-lsp analyze` but not with the VS Code extension. It took me a bit to realize that this only occurred in non-strict mode and `luau-lsp analyze` wasn't recognizing the `.luaurc` because I hadn't specified `--base-luaurc`.

**Comment by JohnnyMorganz** [comment]
It should already be searching for a .luaurc, if it isn't then that is a bug

**Comment by JohnnyMorganz** [comment]
Where did you run `luau-lsp analyze`.
It seems, given the following directory structure
```
base/
    testing/
        data/
            test.luau
    .luaurc
```
With luaurc setting "LocalUsed = false", I get the following results:

- **cwd: `base/`** LocalUnused lint is silenced
- **cwd: `base/testing`** LocalUnused lint is **not** silenced
- **cwd: `base/testing/data`** LocalUnused lint is **not** silenced

It should be silencing in all 3 cases imo, so this is a bug

**Comment by Qualadore** [comment]
I'm pretty confident I ran it from the base directory of my project which directly contains the `.luaurc` file.

**Comment by TreehouseFalcon** [comment]
I also ran into this issue yesterday when setting up a CI task. The `.luaurc` file was in the project root directory and was throwing lints on both of the rules I had defined until I explicitly specified the `--base-luaurc=.luaurc` flag

```json
{
	"lint": {
		"LocalShadow": false,
		"ImplicitReturn": false
	}
}
```
