### ISSUE TITLE
Type documentation ignored when type is `typeof()`

### ISSUE THREAD

**Issue by Qualadore** [JohnnyMorganz/luau-lsp#286]
```lua
local function f()
	return {}
end

--- Comment.
type x = typeof(f())

--- Comment.
type y = {}

local _x: x = f()
local _y: y = f()
```

Hovering over `_y` but not `_x` in VS Code with the Luau-LSP extension will show the comment.

**Comment by JohnnyMorganz** [comment]
This is not a bug, but just a limitation of the current data we have. We are unable to track the source of a type declared using `typeof`, so can't attach comment data
