### ISSUE TITLE
"Fill Call Arguments" should erase filled argument when replacing with literal

### ISSUE THREAD

**Issue by Qualadore** [JohnnyMorganz/luau-lsp#301]
Once I type `"`, `className` should be replaced with `""` instead of `"className"`.
[Code_Nrfy00dzZW.webm](https://user-images.githubusercontent.com/93345551/219884855-f0ab89d4-120e-4d8a-b6f4-c6dee4e54f41.webm)

**Comment by LastTalon** [comment]
This is controlled in part by the vscode setting `editor.autoSurround`. Perhaps the extension can add additional language configurations for this? But this is something vscode does normally for any languages that define bracket pairs.

**Comment by JohnnyMorganz** [comment]
Yup, this is from VSCode as it wraps highlighted text when typing `"`, rather than replacing it.
Not sure if there is a setting that we can specify to stop this from happening specifically for filled call arguments

**Comment by LastTalon** [comment]
> Not sure if there is a setting that we can specify to stop this from happening specifically for filled call arguments

This issue talks a bit about how this interacts with the language configuration for bracket pairs. I don't think it solves it precisely.

In any case, this is definitely not something I would personally want changed. This is how I expect my editor to act; its how it acts everywhere else with snippets/autocompletion/highlighting.

**Comment by JohnnyMorganz** [comment]
Going to close this as a wont-fix. This is a VSCode thing rather than a language server one
