### ISSUE TITLE
server not yet received configuration for diagnostics

### ISSUE THREAD

**Issue by dxgi** [JohnnyMorganz/luau-lsp#302]
receives the error upon onDidOpenTextDocument and onDidChangeTextDocument, making my own monaco-editor with luau-lsp

![image](https://user-images.githubusercontent.com/61899298/219986309-f9e8c43d-11cc-4256-bb64-f30d5fd9c2eb.png)

**Comment by JohnnyMorganz** [comment]
This is an expected error that the client should handle gracefully (we send a server cancelled message and ask for retrigger).
Feel free to ignore / silence it

**Comment by JohnnyMorganz** [comment]
It should no longer happen once the client sends over the official configuration.
This is typically done through a `workspace/didChangeConfiguration` response-> not sure if Monaco supports that?

Alternatively, disable the `didChangeConfiguration` client capability

**Comment by JohnnyMorganz** [comment]
Going to close this issue. Let me know if you are still having problems, but I have seen other monaco users not have this problem
