### ISSUE TITLE
Delayed autocomplete after typing return in an explicitly typed function

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#304]
Autocomplete seems to be delayed after typing return in an explicitly typed function. I recorded an example below, where autocomplete works fast in function b, but is laggy in function a. This problem does not occur in Roblox Studio.

https://user-images.githubusercontent.com/68730440/220328571-909efd4d-bcae-4ce1-a1dc-024129cfc463.mp4

**Comment by JohnnyMorganz** [comment]
I've opened a query with Luau about this https://github.com/Roblox/luau/discussions/847

**Comment by JohnnyMorganz** [comment]
This is fixed in the latest Luau 0.566, will temporarily require enabling the FFlag `LuauAutocompleteSkipNormalization`
