### ISSUE TITLE
Incorrect autocomplete for singleton strings inside if-statements

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#309]
When I begin to compare a singleton string against a constant, I get incorrect autocomplete suggestions until I type a second double quote. Below I have posted a video of the buggy autocomplete behavior.

https://user-images.githubusercontent.com/68730440/222975663-53c9c059-08f2-4832-b3f7-fdc1eb1c2dd2.mp4

Here is my code example: 
```lua
--!strict
type Direction = "Left" | "Right"
local dir: Direction = "Left"

if dir == "Right" then
end
```

This issue does not happen in Roblox Studio as pictured below.
![image](https://user-images.githubusercontent.com/68730440/222975527-49325e99-33a5-4dd1-a098-7e9406870943.png)

**Comment by JohnnyMorganz** [comment]
Typically, as you type it out, it will autocomplete quotes appropriately with your cursor in between, so this isn't an issue:

https://user-images.githubusercontent.com/19635171/223760153-88de7809-f124-4552-8841-a3c8abc1ad4d.mp4

It looks like if you try completing it after the `then` is already present, it doesn't do this though. That is a VSCode limitation it seems, and is not something we can fix

https://user-images.githubusercontent.com/19635171/223760607-5bbc0476-5255-4753-8eb6-0f32e67a6156.mp4

Regardless, it looks like some of the autocompleting is wrong, but may be difficult to fix. This is an upstream problem, and I'll report it there

**Comment by JohnnyMorganz** [comment]
This was fixed in Luau and should now be resolved
