### ISSUE TITLE
Add tree-sitter grammar

### ISSUE THREAD

**Issue by BlockOG** [JohnnyMorganz/luau-lsp#316]
Adding tree-sitter grammar would allow for editors like [helix](https://helix-editor.com) to have luau syntax highlighting.

**Comment by BlockOG** [comment]
Actually, you should support it too

**Comment by JohnnyMorganz** [comment]
A tree-sitter grammar is unrelated to this project, as its an independent feature to the language server.
I did create one a long time ago, but it is not maintained https://github.com/JohnnyMorganz/tree-sitter-luau
You may be interested in building off that, or making your own
