### ISSUE TITLE
Cannot intelligently infer type of re-defined parameters with default values

### ISSUE THREAD

**Issue by cyrus01337** [JohnnyMorganz/luau-lsp#32]
Upon defining a parameter with an optional type, re-declaring the parameter causes the following error(?) to be raised:
```
local iterations: number?
TypeError: Type 'number?' could not be converted into 'number' Luau(1000)
```
I would assume this is an internal error raised by the extension, regardless it's to be expected that the inferred type becomes `number` after re-defining the parameter as it then becomes impossible for it to be `nil`.

Minimal reproduction code snippet:
```lua
local function count(iterations: number?)
    iterations = iterations or 10  -- type remains "number?"

    for i = 1, iterations do  -- error raised here
        print(i)
    end
end
```

Type-casting the parameter upon usage and forcing the type to `number` silences the error despite the odd approach:
```lua
for i = 1, iterations::number do
    print(i)
end
```

If there are any mistakes made/lacking information, do let me know and I will make edits accordingly.

**Comment by JohnnyMorganz** [comment]
This is a Luau error - I would recommend transferring this issue upstream: https://github.com/Roblox/luau

**Comment by JohnnyMorganz** [comment]
Closing in favour of upstream issue
