### ISSUE TITLE
Diff view causes repeated errors while displaying inlay hints

### ISSUE THREAD

**Issue by LastTalon** [JohnnyMorganz/luau-lsp#321]
With inlay hints enabled, displaying the vscode diff view causes numerous errors to repeatedly show, such as:

```
[Error - 3:23:34 PM] Request textDocument/inlayHint failed.
  Message: basic_string::substr: __pos (which is 140416418683905) > this->size() (which is 2290)
  Code: -32603 
```

**Comment by JohnnyMorganz** [comment]
I think we should disable the LSP on the old file in diff view - we cannot really provide useful information. I think this is what other language servers do

**Comment by LastTalon** [comment]
That sounds reasonable to me. I can try and look into some other LSPs and how they handle it.
