### ISSUE TITLE
Cannot detect types from child module tied to & when requiring parent module

### ISSUE THREAD

**Issue by cyrus01337** [JohnnyMorganz/luau-lsp#33]
### Context
I have a module labelled `Utils` that stores many helper functions I like to use, I also have a `Types` child module internally required and set to `Utils.Types`.

### Problem
Typically, "type modules" would work as predicted where types pertaining to `Utils.Types` (when set as a variable, i.e. `local Types = Utils.Types`) would evaluate accordingly - Roblox LSP abides by this as a reference. The module is instead perceived as an empty table shown below:
```
local Types: {|  |}
```

Typehints used also raise the following error:
```
TypeError: Unknown type 'Types.Array' Luau [1001]
```

### Reproduction
[Here's an example package](https://www.roblox.com/library/9895373342/Cannot-detect-types-from-child-module-tied-to-wh) if you'd rather skip the setup.

Create 2 modules - a type module and a parent module that requires then sets the type module to a property within itself (e.g. `{ Types = require(...) }`). Create a script that requires the parent module and attempt to use the types stored within it, you should run into the same problems as described.

Sorry for the loopy name and post by the way, couldn't think of a better way to put my point across. Feel free to change the name to something more coherent or make suggestions.

**Comment by JohnnyMorganz** [comment]
Hey, sorry to keep redirecting you but this is also a Luau issue (the same problem occurs in Studio for example).

This was also brought up by someone else, and this was the response from zeux:
> Types aren’t first class, so the concept of “table type inside a table” doesn’t exist. As such you can’t really get the type from a local. We support a very constrained way to get these from modules only because we currently don’t have explicit imports. Effectively you can think of local foo = require as a very special syntax type checker recognizes. Not as a general mechanism. The hope is in the future at some point it gets “replaced” (augmented) by first class imports.

What RobloxLsp does is not what Luau supports and deviates from the Luau system.

**Comment by cyrus01337** [comment]
No worries, a workaround for me involves _not_ nesting modules and instead directly requiring the type module which is suitable for my use-case. Could you possibly link the discussion for anyone else that may be encountering a similar problem? I'm more than happy to close this issue afterwards.

**Comment by JohnnyMorganz** [comment]
It was mentioned in the Roblox OSS Discord: https://discord.com/channels/385151591524597761/906369439262461992/976919343038341211
