### ISSUE TITLE
Exported types do not resolve when referenced through a parameter of a required module

### ISSUE THREAD

**Issue by SnowdustDev** [JohnnyMorganz/luau-lsp#333]
```lua
-- Simple module script with one type as an example
local TypeModule = {}

export type NumOrString = number | string

return TypeModule
```

```lua
-- Module that gets required by many other scripts
local ParentModule = {}

-- import our type module that has a long or unstable path 
local typeModule = require(game.ReplicatedStorage.Types.NetworkedTypes.TypeModule)
local num1: typeModule.NumOrString -- works!

-- add type module to our ParentModule, so we don't need to needlessly retype path. can just use this reference
ParentModule.typeModule = typeModule

return ParentModule
```

```lua
-- Imagine this is one or many child modules
local ChildModule = {}

local ParentModule = require(game.ReplicatedStorage.ParentModule)

-- get our reference to the type module
local typeModulePointer = ParentModule.typeModule
local num2: typeModulePointer.NumOrString 	-- error, even though it's correct :(

return ChildModule
```

**Comment by JohnnyMorganz** [comment]
Unfortunately, that is not correct. Exported types are not attached to the return table, they are special cases that get imported into the scope where the require is present.

To be able to do this, you need to re-export any imported types in ParentModule, then use ParentModule.NumOrString

**Comment by SnowdustDev** [comment]
Ah I see, interesting. Thank you for the workaround! 
Although, isn't it redundant to re-write every type just for it to export properly? Do you happen to know why exported types aren't included in a return? 

There's a better workaround if we instead keep a reference to the modulescript, and then require it within a child module so the types are available there. But requiring a reference to a modulescript does not resolve the module for typechecking. Not sure if that's a bug or intended, could do another issue if needed.

As an aside, my example above works fine with RobloxLSP, and that functionality makes it much nicer to use types at scale across a project.

**Comment by JohnnyMorganz** [comment]
This is a limitation that comes from Luau, which Roblox LSP is technically not compliant with.
You'll find the same problem in Roblox Studio. If you're interested in a feature request to improve the UX, I would recommend opening one over at https://github.com/Roblox/luau

> But requiring a reference to a modulescript does not resolve the module for typechecking. Not sure if that's a bug or intended, could do another issue if needed.

I *believe* this might be intended, but the best way to confirm is to also check in Studio. If it doesn't work there, then I don't expect it to work here too. I imagine the problem is "tracing" the require across modules

**Comment by JohnnyMorganz** [comment]
To quote what zeux said about this behaviour a while back:

> Types aren’t first class, so the concept of “table type inside a table” doesn’t exist. As such you can’t really get the type from a local. We support a very constrained way to get these from modules only because we currently don’t have explicit imports. Effectively you can think of local foo = require as a very special syntax type checker recognizes, Not as a general mechanism. The hope is in the future at some point it gets “replaced” (augmented) by first class imports

**Comment by LastTalon** [comment]
There's already issues open related to this sort of thing as well. https://github.com/Roblox/luau/issues/872
