### ISSUE TITLE
Need help with C++ LSP client 

### ISSUE THREAD

**Issue by Mararok** [JohnnyMorganz/luau-lsp#335]
I want to plug LSP into my UE5 game (in-game code editor). Is there any C++ client that can connect to the server via stdin? 

Alternativly, any advice on sending capabilities in "initialize" from lsp.

I started with native lua(but luau is better for games)
https://github.com/alextsao1999/lsp-cpp
and
https://github.com/LuaLS/lua-language-server

but client capabilities are diffrent on handshake in logs and "didOpen" not working properly

**Comment by Mararok** [comment]
@JohnnyMorganz  Monaco Editor was

**Comment by Mararok** [comment]
@JohnnyMorganz embed Monaco Editor was awesome idea 😍. It's working in Unreal Engine WebBrowser widget and now I can even use typescript as my programming language for game.
Before I can't use it, because all LSP servers are for nodejs and I can't embed node to  game.

It's crazy... js served from http server embendded in game transpile ts from editor and back to server where I can run it. 

Thx, for idea, You saved months of working on custom editor and LSP client 😅

**Comment by JohnnyMorganz** [comment]
Glad it worked!
