### ISSUE TITLE
TypeError: Unknown global '----local' Luau(1001)

### ISSUE THREAD

**Issue by Tygo01** [JohnnyMorganz/luau-lsp#34]
![image](https://user-images.githubusercontent.com/98230617/173891346-35584808-1846-4f6e-aef9-be887b30ab1e.png)

**Comment by JohnnyMorganz** [comment]
Strange, it looks like the file might have gotten out of sync. Does this always happen? If you restart VSCode is it fixed?

**Comment by JohnnyMorganz** [comment]
If it happens again, do let me know - also if you find out any concrete reproduction steps that would be great.

I think there might be a bug somewhere in my text document syncing

**Comment by JohnnyMorganz** [comment]
I think https://github.com/JohnnyMorganz/luau-lsp/commit/90723b8dd2da050e9a606c50479d23f754509dca may actually have fixed this issue (available in 1.5.1).

Going to leave this issue open for a week to see if it still occurs. If not, then I'll mark this as fixed

**Comment by JohnnyMorganz** [comment]
Assuming this issue has been fixed
