### ISSUE TITLE
Request: Add support for Argon code-syncing tool

### ISSUE THREAD

**Issue by Zodanim** [JohnnyMorganz/luau-lsp#340]
[Argon](https://github.com/DervexHero/Argon) is a code-syncing tool similar to Rojo but with a more intuitive and user-friendly approach. It has actually working two-way sync, a powerful and customizable Roblox Studio plugin, support for live project structure changes, and easy one-click project porting between VS Code and Roblox Studio.

Rojo is very unintuitive at times, with inconsistent naming conventions between the project file and .meta.json files, general syncing issues, not being able to change the project format without issues, so forth. Furthermore, [the primary Rojo maintainer himself has mostly stepped down from the project](https://lpg.space/post/2022-11-07-next-chapter/), stating:

> "This is the right move for me and is overdue. I hope that Rojo serves as a good foundation for the next generation of developers who want to solve the same problems that I did."

I among other people find Argon to be more efficient and enjoyable to use when you don't need things like `rojo build`, which for me is most cases since I primarily just work on games, the main difference in plugin support is the [project file format](https://github.com/DervexHero/Argon/wiki/VSC-Extension-Explained#project-file) and the [file naming](https://github.com/DervexHero/Argon/wiki/Managing-Instances#creating-scripts).

Adding Argon support to Luau LSP would significantly improve the workflow for many developers me included. Right now I use Rojo + Roblox LSP, which works but is not as efficient or hassle-free as one would want from a code-syncing workflow, what I'm not saying is that Rojo should be replaced, it has it's own great uses such as being able to build model files unlike Argon right now, Argon is just an alternative way of accomplishing the same task, better suited for some situations.

Could Argon support please be considered?

**Comment by JohnnyMorganz** [comment]
Luau LSP does not need to add anything special for Argon to be supported.
All you need to do is create a `sourcemap.json` file in the root of your workspace, in a similar structure to what `rojo sourcemap` emits, that describes your whole project layout. Either Argon could create a command to do this, or you can create it yourself. You should turn off the `luau-lsp.sourcemap.autogenerate` setting but **keep `luau-lsp.sourcemap.enabled` on**

Once you have the sourcemap file, Luau LSP should work without issue

**Comment by Zodanim** [comment]
Oh I see, thank you for the fast answer, I did see before that I could turn off auto-generating sourcemaps but didn't exactly understand what it was for, I went through a couple sourcemaps and I think I understand its format. I'll build my own tool for this, thanks for nudging me in the right direction!

**Comment by JohnnyMorganz** [comment]
No problem, let me know if you have any issues or if anything should be explained better!
