### ISSUE TITLE
Instance autocomplete for `PlayerGui` is broken

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#345]
I upgraded to `v1.19.0` and now instance autocomplete doesn't work for `LocalPlayer.PlayerGui` as shown below.
![image](https://user-images.githubusercontent.com/68730440/234774849-a45774bf-5e34-4a26-bf35-003734051778.png)
Restarting VSCode a few times and reconnecting to the Luau language server studio plugin doesn't fix it, however when I revert to `v1.18.1`, instance autocomplete for PlayerGui and its children works again. I will note that I did not change any workspace plugin settings when switching between the two versions.

**Comment by JohnnyMorganz** [comment]
Does this still happen if you disable the `luau-lsp.index.enabled` setting?

**Comment by ArchLand64** [comment]
Yes. I just disabled `luau-lsp.index.enabled`, reloaded VSCode, and reconnected to the studio plugin and instance autocomplete is still broken for `PlayerGui`.

**Comment by ArchLand64** [comment]
Here are my settings for luau-lsp if that helps: 
```json
	"luau-lsp.diagnostics.workspace": true,
	"luau-lsp.autocompleteEnd": true,
	"luau-lsp.sourcemap.rojoProjectFile": "default.project.json",
	"luau-lsp.inlayHints.parameterNames": "none",
	"luau-lsp.inlayHints.parameterTypes": false,
	"luau-lsp.hover.showTableKinds": false,
	"luau-lsp.fflags.sync": true,
	"luau-lsp.fflags.enableByDefault": false,
	"luau-lsp.plugin.enabled": true,
	"luau-lsp.hover.multilineFunctionDefinitions": false,
	"luau-lsp.fflags.override": {
		"LuauCompleteTableKeysBetter": "True",
		"LuauAutocompleteSkipNormalization": "True",
		"LuauTinyControlFlowAnalysis": "True"
	},
	"luau-lsp.diagnostics.strictDatamodelTypes": false,
	"luau-lsp.completion.imports.enabled": true,
	"luau-lsp.completion.imports.requireStyle": "alwaysAbsolute",
	"luau-lsp.completion.imports.separateGroupsWithLine": true,
	"luau-lsp.completion.imports.suggestServices": true,
	"luau-lsp.completion.imports.suggestRequires": true,
	"luau-lsp.index.enabled": false,
```
