### ISSUE TITLE
Autocomplete Doesn't Automatically Select First Result In Some Cases

### ISSUE THREAD

**Issue by ghost** [JohnnyMorganz/luau-lsp#350]
In some cases such as:

```lua
local ReplicatedStorage = game:GetService("ReplicatedStor
```
.. completions are generated, but none are selected by default.

This means that you must manually click the first result in the list or use the arrow keys, rather than just pressing tab to complete.

The first result is automatically selected in other cases (like "GetService" in the GIF below), so this seems like it could be a bug.

I've only noticed this issue occurring in GetService so far, but it could be present elsewhere that I haven't detected.

![Code_lB8CBPtGuQ](https://user-images.githubusercontent.com/130782171/235470705-da5cd497-69b9-456a-866c-cdfcdfef704d.gif)
![AutoCompleteNotSelectingFirstResult](https://user-images.githubusercontent.com/130782171/235470728-15455c38-2018-4a0c-af20-ba715c7ec6c0.png)

**Comment by JohnnyMorganz** [comment]
I can't reproduce this, the first item is always selected for me.

This seems more like a VSCode issue than the language server - do you have any VSCode settings modified?

**Comment by JohnnyMorganz** [comment]
Ah good find, thank you. That looks like the cause.

cc @Barocena I think you said you also suffer this issue?
