### ISSUE TITLE
Incorrect hover and autocomplete types

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#358]
The following code does not produce type errors, but provides incorrect types in hover and autocomplete after the line of code refining `obj` as a `Tool`.
```lua
local obj: unknown = Instance.new("Tool")
if typeof(obj) == "Instance" then
	print(obj)
	if obj:IsA("Tool") then
		print(obj) --// typed as "never", which is incorrect
	end
end
```

**Comment by JohnnyMorganz** [comment]
After a lot of debugging, this seems to be caused from the FFlag `LuauOnDemandTypecheckers`, and disabling it resolves the issue

**Comment by JohnnyMorganz** [comment]
https://github.com/JohnnyMorganz/luau-lsp/commit/02ad9f0db1a9b89f8e848dc304688ceceaacfdff should alleviate the problems encountered here

**Comment by JohnnyMorganz** [comment]
This issue should be resolved

**Comment by ArchLand64** [comment]
This bug still happens with the following code:
```lua
for _, obj in workspace:GetDescendants() do
	if obj:IsA("UIScale") then
		print(obj) --// UIScale incorrectly typed as "never"
	end
end
```

**Comment by JohnnyMorganz** [comment]
> This bug still happens with the following code:
> 
> ```lua
> for _, obj in workspace:GetDescendants() do
> 	if obj:IsA("UIScale") then
> 		print(obj) --// UIScale incorrectly typed as "never"
> 	end
> end
> ```

I cannot reproduce that on latest main version
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/19635171/ea2809c3-d7f1-4dc3-8cb5-918e85d19cfa)

**Comment by ArchLand64** [comment]
Luau-lsp 1.21.0 just solved this bug for me.
