### ISSUE TITLE
Crash on minimal lua file in 1.20.0

### ISSUE THREAD

**Issue by SteveDE** [JohnnyMorganz/luau-lsp#363]
Loving the extension - not sure yet the issue, but 1.20.0 has been crashing my simple test files. I removed my definition file, uinstalled, reinstalled. Only the new version suffers from this, I'm at VS Code 1.78.1.

`function Crash()
    local someValue = 2.0
    someValue = someValue + 1.0 -- crash
end`

Installing the prior version works.

Output:
[Trace - 5:04:23 PM] Sending response 'workspace/inlayHint/refresh - (4)'. Processing request took 0ms
[Trace - 5:04:23 PM] cannot find workspace for file:///s%3A/Evolution/Tests/Scripts/LuauTypeTest.lua
[Trace - 5:04:23 PM] Received response 'textDocument/documentLink - (4)' in 2ms.
[Trace - 5:04:23 PM] cannot find workspace for file:///s%3A/Evolution/Tests/Scripts/LuauTypeTest.lua
[Trace - 5:04:23 PM] Received response 'textDocument/inlayHint - (5)' in 2ms.
[Trace - 5:04:23 PM] cannot find workspace for file:///s%3A/Evolution/Tests/Scripts/LuauTypeTest.lua
[Trace - 5:04:23 PM] Received response 'textDocument/diagnostic - (6)' in 2ms.
[Trace - 5:04:23 PM] Sending request 'textDocument/diagnostic - (7)'.
[Trace - 5:04:23 PM] cannot find workspace for file:///s%3A/Evolution/Tests/Scripts/LuauTypeTest.lua
[Trace - 5:04:23 PM] Received response 'textDocument/diagnostic - (7)' in 1ms.
[Trace - 5:04:23 PM] Sending request 'textDocument/foldingRange - (8)'.
[Trace - 5:04:23 PM] cannot find workspace for file:///s%3A/Evolution/Tests/Scripts/LuauTypeTest.lua
[Trace - 5:04:23 PM] Received response 'textDocument/foldingRange - (8)' in 1ms.
[Trace - 5:04:23 PM] Sending request 'textDocument/documentSymbol - (9)'.
[Trace - 5:04:23 PM] cannot find workspace for file:///s%3A/Evolution/Tests/Scripts/LuauTypeTest.lua
[Trace - 5:04:23 PM] Received response 'textDocument/documentSymbol - (9)' in 0ms.
[Trace - 5:04:23 PM] Sending request 'textDocument/semanticTokens/full - (10)'.
[Trace - 5:04:23 PM] cannot find workspace for file:///s%3A/Evolution/Tests/Scripts/LuauTypeTest.lua
[Error - 5:04:23 PM] The Luau Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by JohnnyMorganz** [comment]
Hey, thanks for the info!
Yeah; some other users also reported crashes.
Will take a look ASAP

**Comment by JohnnyMorganz** [comment]
I've scheduled v1.20.1 for a release which should be out in ~15-20mins. Sorry for the inconvenience!
