### ISSUE TITLE
Extend "Autocomplete End" Support to Call Argument Functions

### ISSUE THREAD

**Issue by LifeBlox** [JohnnyMorganz/luau-lsp#368]
Currently in regular situations like:
```lua
local function test()
--
-- end

local test = function()
--
-- end
```
Luau-LSP automatically inserts the "end" operator when hitting return.

However for situations like the following:
```lua
workspace.Changed:Connect(function()
-- )

task.spawn(function()
-- )

```
No "end" operator is inserted when hitting return.

It appears this only occurs for in-line functions passed as arguments in functions.

I propose that support for the autocompletion of the "end" operator in these situations be added.

### GIF Demos

**"end" completion working properly:**
![Code_7tVdLhwwqf](https://github.com/JohnnyMorganz/luau-lsp/assets/132496834/b95f7b63-ea6d-4afd-8549-8b2e69e9b68b)

**"end" completion working improperly:**
![Code_x6u1hGipem](https://github.com/JohnnyMorganz/luau-lsp/assets/132496834/31156e0c-97c2-4cad-b733-62705f1771b8)

**Comment by JohnnyMorganz** [comment]
The second one is probably because you are in snippet mode (you can see this by the light grey box covering the function)

Can you try disabling the setting `editor.suggest.snippetsPreventQuickSuggestions` and see if it autocompletes?

**Comment by LifeBlox** [comment]
> The second one is probably because you are in snippet mode (you can see this by the light grey box covering the function)
> 
> Can you try disabling the setting `editor.suggest.snippetsPreventQuickSuggestions` and see if it autocompletes?

Still no luck unfortunately 
![Code_18CyamrBTv](https://github.com/JohnnyMorganz/luau-lsp/assets/132496834/a8d960e6-881d-40bb-b166-f5c18e985cbf)
