### ISSUE TITLE
VS Code plugin does not recognize type "unknown"

### ISSUE THREAD

**Issue by AmberGraceSoftware** [JohnnyMorganz/luau-lsp#373]
The following code snippet emits a warning in VS Code, but not in Roblox Studio:
```lua
--!strict

--[[
    @param passedIn: unknown - The value to check
    @return boolean - Whether or not the passed in value is an Observable.

    This function checks if the passed in value is an Observable.
]]
local function IsObservable(passedIn: unknown): boolean
    if typeof(passedIn) ~= "table" then
        return false
    end

    return (passedIn :: any)._dectype == "Observable"
end

return IsObservable
```
<img width="858" alt="image" src="https://github.com/JohnnyMorganz/luau-lsp/assets/131925693/78bcfc50-0bcf-4700-8010-29f34dba1858">

**Comment by JohnnyMorganz** [comment]
This is not the correct plugin. Your warning is coming from Roblox LSP, not the Luau Language Server, which uses a different typing system

https://github.com/NightrainsRbx/RobloxLsp

**Comment by AmberGraceSoftware** [comment]
Oh! I didn't realize I had both installed, my bad! Thanks, VS code extension sync.
