### ISSUE TITLE
PlayerGui should always exist in Player

### ISSUE THREAD

**Issue by Dev0mar** [JohnnyMorganz/luau-lsp#384]
When attempting to index the playergui via Player.PlayerGui (or using FindFirstChild) Luau-LSP throws an error saying that PlayerGui could be nil. 

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/3249781/a0f72382-4050-4b4c-aa51-cf4239608853)

**Comment by JohnnyMorganz** [comment]
I just tested this out and `player.PlayerGui` seems to work fine
