### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by bondhemlig** [JohnnyMorganz/luau-lsp#395]
Type: <b>Bug</b>

it loaded forever as it was diagnosing 1000+ files, and never loaded require paths and when it did it did not give autocompletions.

Extension version: 1.21.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.36GB free)|
|Process Argv|C:\\Users\\Elias\\Favorites\\Documents\\GitHub\\major-framework --crash-reporter-id 717926b4-a2bd-4468-b529-bc96829db9ba|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
ecj1e332:30736112
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
e440d664:30770001
pythonidxptcf:30772540
pythondjangots:30772535

```

</details>

**Comment by JohnnyMorganz** [comment]
Can you try the nightly extension version? This should be improved. Its available at https://github.com/JohnnyMorganz/luau-lsp/actions/runs/5328890585

Alternatively, maybe try disabling the `luau-lsp.index.enabled` setting - does that help?

**Comment by JohnnyMorganz** [comment]
Will close this issue due to no response. If you are still having problems, feel free to reopen
