### ISSUE TITLE
Ignore type errors caused by lack of a sourcemap file

### ISSUE THREAD

**Issue by hoontee** [JohnnyMorganz/luau-lsp#399]
Type errors for `require()`, `game`, `script`, etc when no `sourcemap.json` file exists should be ignored.
These should instead be typed as `any`.

**Comment by JohnnyMorganz** [comment]
The errors are useful to highlight that no sourcemap is present, or there is an issue with it.

If you use non strict mode, it shouldn't error

**Comment by hoontee** [comment]
Can it be an extension setting?

**Comment by JohnnyMorganz** [comment]
What is your usecase for this? I'm curious why one would not wish for these variables to be typed even though they are used.

It will be unlikely to prevent the require errors, but we could potentially suppress the others

**Comment by hoontee** [comment]
After opening this issue, I added sourcemap support to [Lync](https://github.com/Iron-Stag-Games/Lync). So I no longer have a use case.

For other tools it would be nice to disable require errors and such if they don't (yet?) generate sourcemaps.

**Comment by JohnnyMorganz** [comment]
Having a sourcemap is pretty much vital otherwise no require will resolve appropriately, so I don't really see the value in suppressing the warning for require in these cases.

It also looks like `game` / `script` etc. already don't error when no sourcemap is present?
