### ISSUE TITLE
LSP does not recover from invalid UTF-8

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#42]
Accidentally typing or pasting a symbol such as these:

`¶` `§` ``

Will emit the following message:

`SyntaxError: Expected identifier when parsing expression, got invalid UTF-8 sequence`

When the symbol is removed, the message does not go away like it does in studio. 
Worth noting is that the error message in studio is slightly different:

`SyntaxError: Expected identifier when parsing expression, got unicode character U+...`

**Comment by JohnnyMorganz** [comment]
Yeah, our unicode support is all over the place right now, need to read up on how to support this better.
