### ISSUE TITLE
Better error message when `rojo` is not found for sourcemap generation

### ISSUE THREAD

**Issue by hoontee** [JohnnyMorganz/luau-lsp#422]
*This issue assumes the change suggested in #414 gets accepted.*

Currently, [Lync](https://github.com/Iron-Stag-Games/Lync) uses a `*.project.json` format different from Rojo.

Lync automatically generates a `sourcemap.json` file while it's running.

Due to Luau LSP's design, it keeps attempting to read the `*.project.json` in order to generate the sourcemap, failing, and emitting errors.

So, Luau LSP shouldn't attempt to generate the sourcemap if `sourcemap.json` exists.

**Comment by JohnnyMorganz** [comment]
You should disable the `luau-lsp.sourcemap.autogenerate` setting if your sourcemap is generated through other means

**Comment by hoontee** [comment]
Yes, I have this setting disabled in my projects.

**Comment by JohnnyMorganz** [comment]
Then the language server should not be trying to read project.json files or creating its own sourcemaps. What kind of errors are you experiencing?

**Comment by hoontee** [comment]
The errors only occur when the setting is disabled.
For context, this was brought up as a question for Lync, so the solution to the error is either vague or the error shouldn't appear.

**Comment by JohnnyMorganz** [comment]
Can you give the exact error message that is occurring?

**Comment by hoontee** [comment]
Typo. Errors when *enabled*.
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/5272529/862e69f8-451e-45e3-8616-20bb9d58456c)
An alternative fix would be to not error if `rojo` is missing.

**Comment by JohnnyMorganz** [comment]
Ah ok, that makes more sense. Yes we can improve the error message
