### ISSUE TITLE
Workspace diagnostics do not respect ignore globs

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#43]
Seems that when workspace diagnostics are enabled they don't respect ignore globs.
I've had this happen when initially opening a workspace in VSCode, and then sometimes periodically thereafter.
A workaround for now is to just open the file that has the diagnostics and close it again.

**Comment by JohnnyMorganz** [comment]
For the files which aren't being respected, are they dependents of the file you are editing? (i.e., do they require the file you are editing). Or are they just general files in the workspace you haven't touched.
Do you have both `luau-lsp.diagnostics.workspace` and `luau-lsp.diagnostics.includeDependents` enabled, or just the first one?
