### ISSUE TITLE
Hoist common methods of `game` in intellisense

### ISSUE THREAD

**Issue by lolmanurfunny** [JohnnyMorganz/luau-lsp#452]
Currently, writing "game:" and then pressing tab will autocomplete `game:Clone()`.
Hoist `:GetService()` to be the top result in the list, it's self-explanatory.
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/77128366/18e4d8ec-2881-4e93-ba15-cf3d23a62d2e)

Also, hide footgun results altogether.
ie: `AncestryChanged`, `:GetActor()`, `:Clone()`, `:Destroy()`, `:FindFirstAncestor()`, etc

**Comment by LastTalon** [comment]
You're probably interested in the `editor.suggestSelection` setting. There are lots of other settings that control how suggestions are presented to you as well. There can probably be some new settings for what suggestions are included, but a lot of the suggestion settings are controlled by the editor, not the LSP.
