### ISSUE TITLE
Support `%Appdata%` in paths

### ISSUE THREAD

**Issue by FlashHit** [JohnnyMorganz/luau-lsp#464]
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/56718716/62221bde-da09-4edf-b9e5-276181e92e9a)
Can I somehow do `%AppData%` instead of `C:\\etc`?

**Comment by JohnnyMorganz** [comment]
Sorry for the delay in getting to this.

I think this is already possible via the tilde expansion that maps to home directory, which we already support.
You can get `%AppData%` by doing `~\AppData\Roaming`, so `~\Warsaw Revamped\gamecontent` would map to `C:\Users\Camer\AppData\Roaming\Warsaw Revamped`.

I don't think we need to support a separate AppData variable, so going to close as wont do. Let me know if you think it would still be worthwhile
