### ISSUE TITLE
Support for darklua

### ISSUE THREAD

**Issue by Stefanuk12** [JohnnyMorganz/luau-lsp#466]
Within my [darklua](https://github.com/seaofvoices/darklua) configuration, I have the following:
```json
"bundle": {
    "modules_identifier": "__DARKLUA_BUNDLE_MODULES",
    "excludes": [],
    "require_mode": {
        "name": "path",
        "module_folder_name": "index",
        "sources": {
            "core": "./src/core",
            "modules": "./src/modules"
        }
    }
},
```

This lets me do `require("core/utilities")` in any file which is really useful. I'm aware there is a way to do this within the settings already, but an automated version would be great (via darklua)

**Comment by JohnnyMorganz** [comment]
This isn't really something for luau-lsp to do. Like you say, there are ways to update the settings to get this done. Developing a fully automated system is a bit overkill, and also requires luau-lsp to unnecessarily understand the config of an unrelated tool.
