### ISSUE TITLE
Type refinements not working

### ISSUE THREAD

**Issue by Stefanuk12** [JohnnyMorganz/luau-lsp#467]
If we have the following code:
```lua
local function CharacterAdded(Player: Player, Character: Model?)
    if not Character then return end
    local Something = Character:WaitForChild("Something")
end
```

The LSP still thinks Character could be nil. This is wrong as per the [docs](https://luau-lang.org/typecheck#type-refinements).

**Comment by JohnnyMorganz** [comment]
Do you have the FFlag syncing setting disabled? This should be available, but if not, you need to enable the `LuauTinyControlFlowAnalysis` flag
