### ISSUE TITLE
RaycastParams is missing members

### ISSUE THREAD

**Issue by Corecii** [JohnnyMorganz/luau-lsp#468]
RaycastParams is missing the following two members:
* `BruteForceAllSlow`
* `AddToFilter(instances: [Instance](https://create.roblox.com/docs/reference/engine/classes/Instance) | [Array](https://create.roblox.com/docs/luau/tables)): void`

(see https://create.roblox.com/docs/reference/engine/datatypes/RaycastParams)

**Comment by JohnnyMorganz** [comment]
Fixed in https://github.com/JohnnyMorganz/luau-lsp/commit/b004ec7f4762b2ea9cefcd402dfdd83112589fab
