### ISSUE TITLE
TypeError: Cannot add metatable to table

### ISSUE THREAD

**Issue by Stefanuk12** [JohnnyMorganz/luau-lsp#469]
This is an error with how definition files are handled. If the type definition of `self` is within the same file as the `car` file, this error does not show. However, if it is within another file, e.g. `types.lua`, then this error shows.

I've attached an example a small project that you can load to test the issue out. It has the workspace settings defined already, so no need to change your settings.
[TypeDefinitionTest.zip](https://github.com/JohnnyMorganz/luau-lsp/files/12777019/TypeDefinitionTest.zip)

**Comment by JohnnyMorganz** [comment]
I think you misunderstood how exported types work. You need to require `types.lua` then use `types.self`:

```lua
local types = require("types")

local Car = {}
Car.__index = Car

export type Car = typeof(setmetatable({} :: types.self, Car))

-- uncomment below to fix the error
-- export type self = {
-- 	Speed: number
-- }

function Car.new(): Car
	local self = setmetatable({} :: types.self, Car)
	
	self.Speed = 100 -- Speed is recognized
	self:Boost() -- Methods too!
	
	return self
end

function Car.Boost(self: Car): ()
	self.Speed += 50 -- self now is typed and recognizes Speed!
end


return Car
```

**Comment by JohnnyMorganz** [comment]
This is a limitation of Luau and definitions files. You should report this to https://github.com/Roblox/luau - but note that definitions files are an unstable internal feature so do not expect much support there yet.
