### ISSUE TITLE
Add a setting for 'skipping' wally linker files in go-to

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#472]
Every single time that I click a link to a Wally package I get taken to the generated linker file and not the actual package, which is where I want to get to. This is probably confusing for new users as well.

I assume this is not within scope for the language server, to be aware of Wally, so maybe like how Rojo sourcemaps are generated in the language client / vscode we could also add some middleware to modify where links go when Wally exists?

**Comment by LastTalon** [comment]
I think it's probably reasonable to have a setting that could allow passing through files that re-export requires. That probably could solve this issue, too.

**Comment by JohnnyMorganz** [comment]
This complicates document link functionality somewhat, since right now document link does not actually need to care (or parse) the contents of the file it is pointing to, it just statically looks up the path given in the expression.

**Comment by JohnnyMorganz** [comment]
> I assume this is not within scope for the language server, to be aware of Wally, so maybe like how Rojo sourcemaps are generated in the language client / vscode we could also add some middleware to modify where links go when Wally exists?

I just thought - this is an interesting point. You can definitely solve this problem externally by mutating your sourcemap. You just need to change the filepath for the wally linker files to point to the direct library file instead - then jumping will work immediately (also you would no longer need a tool like wally-package-types).

The above solution won't need any changes on the language server side - we just take the sourcemap and roll with it.
