### ISSUE TITLE
TypeError thrown when indexing workspace (attempting to resolve despite no local directory)

### ISSUE THREAD

**Issue by josh-hurst** [JohnnyMorganz/luau-lsp#477]
This TypeError is being thrown when I index a descendant of any service:
![Screenshot 2023-10-20 at 4 31 36 PM](https://github.com/JohnnyMorganz/luau-lsp/assets/146042820/efc235ab-8876-4584-abef-1cfb5b4d77a8)

I mention workspace specifically because I have no local directory for Workspace nor is it in my sourcemap so I don't think it should be throwing this error. I did try to add Workspace to my project and use your studio plugin, which ended up giving me a 404 error with the details "Route not found: /full". Though, since the plugin is actually sending the request, but being met with a 404, I suspect this is an issue on my end.

If this (TypeError) is intentional behavior, I think errors probably should not be thrown when indexing a service, or any "virtual object" created by the LSP which has unknown descendants.

**Comment by JohnnyMorganz** [comment]
Do you have `luau-lsp.diagnostics.strictDatamodelTypes` enabled?
With this disabled, workspace and other DM types should resolve to any and you won't get any type errors

**Comment by josh-hurst** [comment]
I do have it disabled but it doesn't seem to be making any difference. Though, I'm using the neovim implementation, so it could possibly be a bug with the setting not being applied from the neovim config. I'll do some debugging with it later today to verify and I'll let you know

**Comment by josh-hurst** [comment]
Hey sorry for the late response. Never was able to resolve it. I looked into the neovim configuration and it seems to be passing the values to the lspconfig fine, and lspconfig is passing my configuration to neovim's lsp client fine. Beyond that I can't tell if there's a problem with the communication between neovim and the LSP, or if it's a problem with the LSP itself. However the configuration on my other LSPs are working fine. Here's the configuration that is being passed into Neovim's lsp.start_client:
```lua
{
   ['luau-lsp'] = {
      diagnostics = {
         strictDatamodelTypes = false
      }
   }
}
```
(contained in the settings field, but this is what is being passed to the server.)

Also, I'm definitely not turning the setting *on* anywhere, so even if there is an issue with the config being passed to the LSP, it should default to off. On a side note, the ability to disable specific diagnostics would be useful and an alternative way to solve this.

**Comment by JohnnyMorganz** [comment]
Unfortunately I cannot find a way to reproduce this in vscode.

But actually, `strictDatamodelTypes` is `true` by default in the C++ side (I am not sure why...):
https://github.com/JohnnyMorganz/luau-lsp/blob/09dd9c9c0dc31a84a544ee25294cc95d7319039c/src/include/LSP/ClientConfiguration.hpp#L12C38-L12C38

So the issue probably stems from the way config is getting passed from neovim -> the language server.

I think I can fix the default on the C++ side to `false`, as that seems unintentional

**Comment by josh-hurst** [comment]
To add one final thing, I'm actually able to reproduce this on command line too with a simple `luau-lsp analyze test.lua --settings=testsettings.json` with test.lua as `print(workspace.test)` and testsettings.json as
```json
{
   "luau-lsp": {
      "diagnostics": {
         "strictDatamodelTypes": false
      }
   }
}
```
It's possible it has something to do with the fact that I'm on MacOS? I'll do some debugging myself on the C++ side and get back to you/push fixes

**Comment by JohnnyMorganz** [comment]
That is because the analyze CLI tool doesn't actually respect that setting in the config. You need to pass `--no-strict-dm-types`.
The reason it doesn't is purely legacy though, maybe we should make it follow the config instead.

https://github.com/JohnnyMorganz/luau-lsp/blob/0399b785fdfd93b1a6bcf753d06f9346979ebc83/src/AnalyzeCli.cpp#L335

The `expressiveTypes` here only comes from the CLI options, but we can make it come from the config instead

**Comment by josh-hurst** [comment]
Oddly enough even with `luau-lsp analyze test.lua --no-strict-dm-types --definitions=path/to/type/definitions` I still get `test.lua(1,7): TypeError: Key 'test' not found in class 'Workspace'`

**Comment by JohnnyMorganz** [comment]
Ah yeah, you also need to provide a sourcemap for that to resolve correctly.
