### ISSUE TITLE
Show path for auto imports

### ISSUE THREAD

**Issue by Weldify** [JohnnyMorganz/luau-lsp#478]
I've got a lot of files with the same name and requiring became kinda tedious. I think that the auto import thingy that pops up should also include part of the file path instead of only the name.

There are a couple approaches that can be taken:

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/66477673/bae01cbf-46f5-4121-a378-5e2b3db2e45a)

1. Only show the difference in paths
`foo.lua | client`
`foo.lua | server`

2. Show the full path
`foo.lua | somefolder/client`
`foo.lua | somefolder/server`

The first option is very unintrusive and concise while the second option is probably a lot simpler to implement and comprehend

**Comment by JohnnyMorganz** [comment]
Is the file path not already displayed in code form in the description?

**Comment by Weldify** [comment]
Not sure. When I use autocomplete it only shows the filename. I'm using it with Roblox by the way

**Comment by JohnnyMorganz** [comment]
Path will now be included like below. Hope it's suitable
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/19635171/b7c55877-3ffa-4bcd-8916-f5fab6422f49)
