### ISSUE TITLE
Incorrect parameters for OrderedDataStore:GetSortedAsync()

### ISSUE THREAD

**Issue by AntarcticWulf** [JohnnyMorganz/luau-lsp#480]
As seen in the attached image, you can see how the lsp expects the user to put 5 arguments for :GetSortedAsync() which is incorrect due to minvalue and maxvalue being optional parameters

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/111803561/9c53c7ea-253c-4897-9451-af55e1c94dc4)

**Comment by JohnnyMorganz** [comment]
I can fix this now. But in future, contributions are welcome to fix!
https://github.com/JohnnyMorganz/luau-lsp/tree/main/scripts#contributing
