### ISSUE TITLE
double-click type inlay hint fails to insert type when type gets truncated

### ISSUE THREAD

**Issue by walksanatora** [JohnnyMorganz/luau-lsp#486]
allow us to copy the inferred types of variables (mainly for when we are too lazy to write it on our own)

**Comment by JohnnyMorganz** [comment]
Can you give an example of what you mean?

Note that Inlay Hints already exist and is something you can enable, and if you double click on an inlay hint, it will automatically get added to your code

**Comment by walksanatora** [comment]
oh really?
...
I just tried double-clicking the inlay hint and it isn't doing anything
because if I hover it is just
```
local module: {|
    add: {|
        i32: <a, b>(lhs: a, rhs: b) -> number,
        i64: <c, d>(lhs: {c}, rhs: {d}) -> {any}
    |},
    allocator: {|
        grow: <e>(memory: {+
            max: any,
            min: any
        +}, num: e) -> number,
        new: <f, g>(min: f, max: g) -> {|
            data: {|  |},
            max: g,
            min: f
        |}
    |},
    band: {|
        i64: (lhs: {number}, rhs: {number}) -> {number}
    |},
    bnot: {|
        i64: (value: {number}) -> {number}
    ... *TRUNCATED*
    ```
if I double-click to highlight whole line it copy/paste as `local module = {}`

**Comment by walksanatora** [comment]
it works on *non truncated* types
but if it truncates the type it then cannot be double-click applied

**Comment by JohnnyMorganz** [comment]
That is intentional - a truncated type we do not have the full type to insert. I question the value of trying to insert a really long type

**Comment by walksanatora** [comment]
so that I can prevent breaking the api when I make future changes

**Comment by walksanatora** [comment]
(and also adding types to generated code which lacks it)

**Comment by JohnnyMorganz** [comment]
Well, you can solve the truncation by modifying the FFlags `LuauTypeMaximumStringifierLength` and `LuauTableTypeMaximumStringifierLength`. Setting them to `0` will disable truncation completely. Note that this will also affect stuff like hover

**Comment by JohnnyMorganz** [comment]
Closing as stale with the above fix. Feel free to reopen if you have anything to add
