### ISSUE TITLE
TypeError: Key not found in class 'LuaSourceContainer'

### ISSUE THREAD

**Issue by cyrus01337** [JohnnyMorganz/luau-lsp#49]
### Problem
Indexing the `script` keyword when attempting to reference children, i.e. `script.Foo`, is met with the error of title.

### Replication
Index the `script` keyword with an unknown property name, which should resolve to the instance it references.

### Workaround
Replacing indexing with `FindFirstChild` method calls silences the error, yet creates strange looking code (maybe biased) with redundant code practice/method misuse. **Be aware that module type inference fails if requiring what's returned.**

**Comment by JohnnyMorganz** [comment]
Question: do you *not* have a sourcemap present when this occurs?

**Comment by cyrus01337** [comment]
I have a source-map generated by the extension and, based on it's output, seemingly regenerates the source-map which I'm assuming is expected behaviour.

**Comment by JohnnyMorganz** [comment]
That is expected behaviour, but that also means this error shouldn't be occuring.... Strange, I'll take a further look

**Comment by cyrus01337** [comment]
Deleting the source-map had no effect if that helps any.
