### ISSUE TITLE
Intellisense not working Neovim

### ISSUE THREAD

**Issue by Nizarll** [JohnnyMorganz/luau-lsp#497]
Here's my mason lspconfig file
plugin seems to work but intellisense and treesitter dont ?
![Screenshot 2023-11-19 200338](https://github.com/JohnnyMorganz/luau-lsp/assets/151186173/9104baac-e959-4add-bf63-c8153be26e8b)

**Comment by JohnnyMorganz** [comment]
Unfortunately I do not manage the neovim setup. Please report your issue to https://github.com/lopi-py/luau-lsp.nvim
