### ISSUE TITLE
Create a way to silence errors

### ISSUE THREAD

**Issue by cyrus01337** [JohnnyMorganz/luau-lsp#501]
Unsure if this is already implemented, however I did sift through the [linting](https://luau-lang.org/lint) and [type-checking](https://luau-lang.org/typecheck) docs without any results. If there could be a way where, similar to [ESLint](https://eslint.org/docs/latest/use/configure/rules#disabling-rules), you're able to temporary disable the linter/given rules for the next line or blocks of code, that'd be solid.

Not sure how much work that would need, or if this is even a job for the LSP in the first place, feedback is greatly appreciated.

**Comment by JohnnyMorganz** [comment]
Yeah, this needs to be solved by Luau directly rather than here. You should make an issue there about it (it might need an RFC too)

**Comment by JohnnyMorganz** [comment]
Going to close this as it's not completely actionable here. I recommend opening an issue on https://github.com/luau-lang/luau or an RFC at https://github.com/luau-lang/rfcs
