### ISSUE TITLE
Provide semantic token info to `for` loop vars

### ISSUE THREAD

**Issue by lolmanurfunny** [JohnnyMorganz/luau-lsp#502]

**Comment by JohnnyMorganz** [comment]
Can you provide an example where this would be useful? I try to reduce unnecessary semantic tokens since they clash with textmate scopes and therefore peoples' personal themes

**Comment by lolmanurfunny** [comment]
This is really a bug, `for` loop variables are inconsistently highlighted. The title is the solution, however, I failed to actually address the problem itself.

The inconsistent syntax highlighting:
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/77128366/fd573e65-c8c6-460d-bac7-bd5d51d048b8)

**Comment by JohnnyMorganz** [comment]
It seems to be we are using two different textmate scopes here, causing the different highlighting. I'm not sure why we decided different ones:
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/19635171/9590d2f9-d400-45d0-bbad-e8af336570c1)
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/19635171/23aaa791-9b7e-4863-811c-72fccfb14ec1)

Maybe it is better to fix the textmate scopes instead. Or, semantic token might be useful

**Comment by lolmanurfunny** [comment]
> Maybe it is better to fix the textmate scopes instead. Or, semantic token might be useful

In preparation for opening this issue, I briefly compared the highlighting of for-loop vars with function params. What I immediately observed was that function params have consistent highlighting and the semantic token.

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/77128366/5f69d379-a732-4c67-a46f-1bb541e46fb8)
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/77128366/d141a676-81b3-4498-828e-6fd17cdfd515)

**Comment by JohnnyMorganz** [comment]
Yeah, the problem here is that there is no semantic token specifically for for loop variables. We could also give them the "parameter" semantic token but that then mixes it with function parameters, which I am not sure I want to do.

**Comment by lolmanurfunny** [comment]
> We could also give them the "parameter" semantic token but that then mixes it with function parameters

Well, considering for loop variables (in the declaration) already possess the "parameter" textmate scope, providing the "parameter" semantic token sounds expected.

Alternatively, provide a setting so the user can decide, however, I'm not sure a bug should hide behind a setting.

**Comment by JohnnyMorganz** [comment]
> Well, considering for loop variables (in the declaration) already possess the "parameter" textmate scope

This is what I mean, I don't think it *should* posses the parameter scope, and maybe we should remove that instead.
I personally believe the parameter scope should be reserved directly for function parameters, as otherwise it can lead to confusion. It would be nice if there was a semantic scope specifically for loop variables.

**Comment by lolmanurfunny** [comment]
> I personally believe the parameter scope should be reserved directly for function parameters, as otherwise it can lead to confusion.

Your approach is mostly based on speculation. I see the token as the more user-friendly option since a number of people, myself included, view for-loop variables as "parameters", and for good reason.
