### ISSUE TITLE
Add option to display Luau compiler remarks alongside code

### ISSUE THREAD

**Issue by grilme99** [JohnnyMorganz/luau-lsp#514]
There are a few fringe use cases when debugging performance where looking at the compiler's remarks output would be helpful. The default way to do this, `luau-compile --remarks`, slows down iteration. What would be better is if Luau LSP could display these remarks alongside my code, such as in a code lens.

Internal Roblox engineers have a workflow like this inside of Roblox Studio:

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/6473667/05f00ae5-cb66-4ee4-be44-68623a65ec68)
_Taken from the OSS discord, code is from a hack week project_

**Comment by LastTalon** [comment]
Should they be a code lens or should they be infos? They seem like they're more likely infos to me and I have those displayed inline alongside warnings and errors using the error lens extension.

**Comment by JohnnyMorganz** [comment]
Another option we have here is opening a readonly document with remarks as comments in the source file when the command is run. @grilme99 do you think that would be suitable? Or would you rather the data is inlined somewhere in the current source file

**Comment by JohnnyMorganz** [comment]
Added the viewer. In the end I decided to do a separate panel, which auto updates as you type / switch files.

I also went ahead and did textual bytecode output too

https://github.com/JohnnyMorganz/luau-lsp/assets/19635171/6d5ea652-7f5f-47fc-acf0-9c823a9de0a0

**Comment by LastTalon** [comment]
> Also, this assumes that everyone using this also uses error lens, unsure how it will look generally.

I think infos (or at least an option to make them infos) would be good even if people aren't using error lens. It's something that you can view regardless of that extension, error lens just makes it very readily apparent. I can understand that mixing it with the other diagnostics can be a problem though.
