### ISSUE TITLE
Add way to hide and/or underline API parts that are only accessible to Roblox engineers (Roblox Security)

### ISSUE THREAD

**Issue by Daw588** [JohnnyMorganz/luau-lsp#515]
I sometimes find myself attempting to use an API method, or property that it is not accessible. I would like to be able to get warned about developer inaccessible API usage, and be able to hide the said API parts so that they don't show up anywhere (e.g., autocomplete).

**Comment by JohnnyMorganz** [comment]
Next release will have a setting `luau-lsp.types.robloxSecurityLevel` (default: `PluginSecurity`) to allow you to configure this setting
