### ISSUE TITLE
Sourcemaps not generating post `wally install`

### ISSUE THREAD

**Issue by jmesrje** [JohnnyMorganz/luau-lsp#521]
Luau-lsp is not generating sourcemaps automatically, particularly after running `wally install`. This forces you to restart your VSCode session.

**Comment by JohnnyMorganz** [comment]
There should be a notification that pops up when this fails. Do you get this? It has a retry button to restart regeneration

**Comment by JohnnyMorganz** [comment]
Been playing around with this and I cannot get it to reproduce anymore after multiple wally install attempts.

Going to close this for now. If you still experience problems with it, let me know.
