### ISSUE TITLE
how to use the Luau Vector3 type with luau-lsp?

### ISSUE THREAD

**Issue by nurpax** [JohnnyMorganz/luau-lsp#523]
I'm trying to typecheck code that's using the Luau 3-vector type.  

But I don't know how to make luau-lsp aware of it?  

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/297823/a2583613-9d39-4252-8395-e90df34f1a4d)

**Comment by nurpax** [comment]
Well, I added this in my types definition.  I guess that's fine :)

```
declare class Vector3
    x: number
    y: number
    z: number
end

declare function Vector3(x: number, y: number, z: number): Vector3
```

Feels like there should be some kind of a better way as I guess vectors are kind of a built-in feature?

**Comment by JohnnyMorganz** [comment]
Vectors aren't special in the type checker,. It's all host environment dependent, on however the env exposes vectors. Indeed the way you have done it should work, and is similar to the way Roblox sets up their vector type

**Comment by nurpax** [comment]
Got it, thanks!  I think I'll have to write a long form blog post about using all these tools together.
