### ISSUE TITLE
Renaming module keys does not update external references

### ISSUE THREAD

**Issue by lolmanurfunny** [JohnnyMorganz/luau-lsp#534]
Renaming a key inside of a module's returned table doesn't automatically update external references. The current workaround is invoking `Rename` on another script's reference to the key.

Given the following code, when `Rename` is invoked on `foo` from within `./module`, the reference inside `./script` will not be updated.

`./module`
```lua
return {
    foo = function() end
}
```

`./script`
```lua
local module = require("./module")

module.foo()
```

**Comment by JohnnyMorganz** [comment]
I cannot reproduce this with the example you gave - it works fine for me.

Have you by any chance disabled indexing in your settings?

**Comment by lolmanurfunny** [comment]
In my codebase, I find that rename in situations which the repro aims to model is hit or miss. Also, indexing was 100% enabled.

**Comment by JohnnyMorganz** [comment]
Will close as cannot currently repro. If you get a reproducible example, more than happy to check it out
