### ISSUE TITLE
Display `sort requires/services` code action available only in requires

### ISSUE THREAD

**Issue by lopi-py** [JohnnyMorganz/luau-lsp#540]
It's a bit annoying to show that code action on every single line:
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/70210066/95d19333-c1ab-4df2-95a9-e7c9b57b384f)
It makes sense to only show the code action available if the current line is a require or game:GetService

**Comment by JohnnyMorganz** [comment]
I think this is an issue with your editor client implementation.

These code actions are specified with a "source" code action kind: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionKind, indicating that the code action applies for the whole file. Your editor shouldn't display a lightbulb on all lines for source actions IMO. This does not happen in VSCode

**Comment by lopi-py** [comment]
Oh yeah, there wss a setting for it
