### ISSUE TITLE
Revert to on-demand rojo sourcemap by default

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/luau-lsp#544]
Switching to a long-living `rojo sourcemap --watch` Rojo process has brought about a few issues:
- "Access denied" errors where the sourcemap process is taking ownership of the opened files
- Watched process is not cleaned up when VSCode closes (this is becasue VSCode only budgets ~5s for *all* extensions to sequentially cleanup, and then forces shutdown. If other extensions take a long time, the luau-lsp deactivate function is never called, and the process is not cleaned up).
- Watched process not restarted when Rojo dies (#521)

We should revert to calling rojo sourcemap on demand by default. Watch should remain, but as an opt in feature

**Comment by LastTalon** [comment]
Not that I am advocating for one solution or the other, but

> Watched process is not cleaned up when VSCode closes (this is becasue VSCode only budgets ~5s for _all_ extensions to sequentially cleanup, and then forces shutdown. If other extensions take a long time, the luau-lsp deactivate function is never called, and the process is not cleaned up).

Why is rojo not started as a sub-process of the extension? Doing it that way means the system will detect it as a sub-process and end it when the parent process is ended so it wouldn't matter if VSCode cleans up your extension.

**Comment by JohnnyMorganz** [comment]
We already spawn rojo as a child process. But I do not think that statement is correct? If a parent process dies before the child completes, the child still continues (with ppid = 1 on unix) - an orphaned process.

**Comment by filiptibell** [comment]
> We already spawn rojo as a child process. But I do not think that statement is correct? If a parent process dies before the child completes, the child still continues (with ppid = 1 on unix) - an orphaned process.

This is correct, child processes will stay alive - and there are some hacky solutions such as [tree-kill](https://www.npmjs.com/package/tree-kill) to solve this in the node ecosystem, maybe vscode/electron should be doing something similar to this upstream actually

**Comment by JohnnyMorganz** [comment]
> there are signals you can set to control this behavior

Yeah, but my understanding is that these signals need to be listened on the child side, not the parent (and rojo is a third party tool). We could make a wrapper script, but seems overkill.

**Comment by LastTalon** [comment]
The signal in question is SIGHUP, which most processes listen to to know when they're supposed to be closed already. They usually get them from things such as terminals closing and whatnot.

I'm a little unsure what the current state of node is because it seems like the default behavior is to kill child processes spawned in node. See: https://stackoverflow.com/questions/30708801/node-js-child-processes-being-killed-when-parent-dies

**Comment by JohnnyMorganz** [comment]
I wonder if the problem stems from the fact that we set `shell: true`. That means what actually gets executed is `bash -c rojo` (or the equivalent for other platforms). So the child process here is actually bash, not rojo which is actually a grandchild. Maybe bash is getting cleaned up, but the grandchild is not and it gets orphaned.

We could reinvestigate the need for enabling shell mode. IIRC, it was because of PATH issues, but maybe it is no longer a problem.

**Comment by JohnnyMorganz** [comment]
I stopped using `shell` mode in the recent update. Would be interested to know if it breaks anything
