### ISSUE TITLE
Incorrect entry kind detection in variables with explicit type definitions

### ISSUE THREAD

**Issue by xactlyblue** [JohnnyMorganz/luau-lsp#550]
Variables with a definition are classified as classes instead of variables, whereas variables with ``any`` or otherwise unknown types are treated as expected. This causes issues in automatic completion systems where options are sorted based on type, making it very non-intuitive.

It should also be noted that in the following example the entry kind misclassification also happens if you don't explicitly state the type. It only functions in the expected way if you **explicitly** state for it to be treated as an ``any``.

| Normal | Explicitly cast to ``any``  | 
|--------|--------|
| ![image](https://github.com/JohnnyMorganz/luau-lsp/assets/43724726/9938bd97-2279-46a3-9101-b3dd9eff0161) | ![image](https://github.com/JohnnyMorganz/luau-lsp/assets/43724726/a23bb415-1d7b-49cb-a2a0-2c6459f2f49d) |

**Comment by lopi-py** [comment]
I seems to only happen with variables holding roblox types
