### ISSUE TITLE
Add an option to disable the custom icon

### ISSUE THREAD

**Issue by ColRealPro** [JohnnyMorganz/luau-lsp#551]
Please add an option in the extension settings to disable the custom icon because it can sometimes override the current icon theme's icon.

Example:

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/64316078/a555a22b-e4dd-4fcc-a104-962f9978aa22)

Should look like:

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/64316078/e33771aa-12cf-42a5-9796-665aa9d52d2b)

Thank you!

**Comment by JohnnyMorganz** [comment]
The icon isn't an override, but a default. Your theme should provide an icon for the "luau" language ID

**Comment by ColRealPro** [comment]
Sorry for the late response, but if that is the case, can this be changed to only set the icon for files with specifically the luau extension and not regular lua extension files?

**Comment by JohnnyMorganz** [comment]
I'm not sure if this is configurable in the extension unfortunately. I would recommend updating the theme
