### ISSUE TITLE
Autocomplete end does not work with `function name()` but works with `local function name()` 

### ISSUE THREAD

**Issue by AridAjd** [JohnnyMorganz/luau-lsp#554]
When you do `function name()`, the `end` is not autcompleted, but when you do `local function name()` (adding the local before function), it properly autocompletes the `end`. This problem occurs with `Autocomplete end` enabled. Here's a video:

https://youtu.be/cxOV6Rla3s0

###### (added link because github doesn't allow vids > 10mb)

**Comment by JohnnyMorganz** [comment]
Underlying issue is https://github.com/luau-lang/luau/issues/1328
