### ISSUE TITLE
Unable to Rename non local Functions or variables

### ISSUE THREAD

**Issue by kalebs-anotheraxiom** [JohnnyMorganz/luau-lsp#568]
When declaring non local Functions as shown below, Or non local variables, you are unable to use F2 Rename to rename the function and or any references

<img width="922" alt="Code_CGUINjKu3K" src="https://github.com/JohnnyMorganz/luau-lsp/assets/127455380/df6b2d13-9dff-4a38-8e54-bd6d3eb4ee1d">

I have a local fix creating a new FindGlobalReferences Luau::AstVisitor and a new findGlobalReferences function inside of LuauExt.cpp which is used as a fallback because non local types have some sort of discrepancy when it comes to exprOrLocal inside of the Rename Operation, It was a bit hacked together so i don't want to open a Pr with it but I could provide my source as a starting point for a fix

**Comment by kalebs-anotheraxiom** [comment]
I have a local fix creating a new FindGlobalReferences Luau::AstVisitor and a new findGlobalReferences function inside of LuauExt.cpp which is used as a fallback because non local types have some sort of discrepancy when it comes to exprOrLocal inside of the Rename Operation, It was a bit hacked together so i don't want to open a Pr with it but I could provide my source as a starting point for a fix

**Comment by JohnnyMorganz** [comment]
Thanks for the info! Will try to take a look this weekend
