### ISSUE TITLE
Optional Object Properties not being Type Hinted Well

### ISSUE THREAD

**Issue by kalebs-anotheraxiom** [JohnnyMorganz/luau-lsp#582]
<img width="577" alt="Code_vbwQncuJ5K" src="https://github.com/JohnnyMorganz/luau-lsp/assets/127455380/377265c1-635b-44cc-98b0-a0ea05662578">

```lua
function TestWithOptionalObject(Val: { Number: number?, String: string? })
	log(Val.Number)
	log(Val.String)
end

TestWithOptionalObject({
	
})
```
Type System isn't properly inferring the two only properties that i realistically want, Is this something that's being addressed sometime later, I can also add whatever Keys i want to TestWIthOptionalObject without it complaining

**Comment by JohnnyMorganz** [comment]
I believe this is a Luau issue, as we get autocomplete from there.
