### ISSUE TITLE
1.16.2 vs 1.16.3

### ISSUE THREAD

**Issue by dxgi** [JohnnyMorganz/luau-lsp#583]
my source code uses 1.16.2, I tried to use the newest version available however I noticed that if I try to something like textDocument/semantic/full or something like textDocument/inlayHint, I get an undefined result. So I tried to traceback and compare what changes were made. I tried to use 1.16. and got the same null result, the uri for the editor is

inmemory://...

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/61899298/0804521b-372d-4579-bff3-b3ed5a406797)
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/61899298/beeb0ea4-2219-448f-8dfa-570f1afe947e)
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/61899298/54a66893-7e5d-473c-94cb-84e3d046210f)
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/61899298/cb4a989d-803a-4907-a191-4eafd8bfb798)
I've added some code to the source and just as I thought

The following commits may be related to my issue

https://github.com/JohnnyMorganz/luau-lsp/commit/728e9adcdf0265249c4a27bd3fe0724171d0279f
https://github.com/JohnnyMorganz/luau-lsp/compare/1.16.2...1.16.3

**Comment by JohnnyMorganz** [comment]
Hey, sorry for the significant delay in responding here.

Indeed I think 728e9adcdf0265249c4a27bd3fe0724171d0279f would likely cause the above error messages.

It seems like the URI you are using for these requests doesn't match the uri you sent for `textDocument/open`, so there is no managed document to look up. Could you double check they match? If they do, then there might be a problem on our side when handling these special types of URIs
