### ISSUE TITLE
Documentation on file contents for `luau-lsp.types.definitionFiles`

### ISSUE THREAD

**Issue by MXKhronos** [JohnnyMorganz/luau-lsp#601]
Hello, I'm requesting for more documentation for my own additional definition files.

What and how are definition files written? Are they `.lua` files containing export types or are they more like this [API Dump](https://github.com/JohnnyMorganz/luau-lsp/blob/8eca6e71d183e3c5218bc73998d1dd55e2ee3630/scripts/README.md)?

Thanks in advance,
Khronos

**Comment by lolmanurfunny** [comment]
https://gist.github.com/Dekkonot/1f678708a3a36866d3c728b8cfb9589e
