### ISSUE TITLE
Add support for `keyof` type operator

### ISSUE THREAD

**Issue by 2jammers** [JohnnyMorganz/luau-lsp#603]
https://github.com/luau-lang/rfcs/pull/16
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/119134081/d3204ab1-1a84-42bf-9a50-65f3e11629e4)

**Comment by JohnnyMorganz** [comment]
This is a Luau thing. The operator exists in the new solver. You can enable the FFlag DebugLuauDeferredConstraintResolution for the new solver. It is unstable
