### ISSUE TITLE
Autocomplete Suggestion for a string index does not fully replace the string.

### ISSUE THREAD

**Issue by zzhabib** [JohnnyMorganz/luau-lsp#607]
Whenever I type a string index into an array and use an autocomplete suggestion, the string does not get fully replaced. Instead, it is concatenated which is not very helpful most of the time.

https://github.com/JohnnyMorganz/luau-lsp/assets/26579319/e8c8fc47-a4f9-49ae-b5bd-33cdaf9e1fa3

**Comment by lolmanurfunny** [comment]
Similar to #479
