### ISSUE TITLE
Missing checks for nil keys for tables and instances

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#61]
Right now, luau lsp does not check for optional variables when indexing a table or instance. 

This code should show a type error because nil keys can never have a value:
```lua
local nameMap: { [string?]: string } = {}
```

This code should also show a type error because targetName may be nil:
```lua
local targetName: string? = nil
workspace[targetName]:Clone()
```

**Comment by JohnnyMorganz** [comment]
This is a Luau issue, I would recommend transferring it there
