### ISSUE TITLE
Wrong string alias used

### ISSUE THREAD

**Issue by brinkokevin** [JohnnyMorganz/luau-lsp#610]
When there are `@Server` and `@ServerPackages` alias setup, luau-lsp points to @Server/Packages/... when attempting to use @ServerPackages

![image](https://github.com/JohnnyMorganz/luau-lsp/assets/8604658/21954a81-6537-494d-a152-ab4173c19f9a)

```lua
-- TypeError: Unknown require: /src/Server/Packages/Lapis.lua
local Lapis = require("@ServerPackages/Lapis")
```

**Comment by JohnnyMorganz** [comment]
Yeah, we could do better here, but the quick fix is indeed to add a trailing slash to the end of your alias.

Going to close this as a wont fix though, as we will switch to Luau's path aliases in future
