### ISSUE TITLE
goto definition on require paths

### ISSUE THREAD

**Issue by itsfrank** [JohnnyMorganz/luau-lsp#612]
This is the one feature I miss the most from lua-ls.

In lua-ls if I have my cursor on the string portion of a require statement, e.g.:
```lua
local foo = require("./f[]oo")` -- where '[]' is my cursor
```
If I hit my "goto definition" hotkey (in my case: `<leader>gd`) it will send me to line 1, column 1 of that file.

This does not seem to work in luau-lsp, it would be a helpful feature to add.

I could see how this would be challenging with Roblox paths however

**Comment by JohnnyMorganz** [comment]
We already support document links as part of the protocol, and we add these for require statements - https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentLink

Are these not sufficient for your usecases? For example in vscode you will see below:
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/19635171/fb9fbb27-1ec1-4da3-bd61-dde768119810)


It's not the same as go to definition protocol, but i don't think it really makes sense here. It sounds like you are using (neo)vim, maybe check what the keybind for follow link is there?

**Comment by lopi-py** [comment]
He seems to be using neovim. I don't think neovim supports lsp's follow link, but other servers (clangd, rust-analyzer, tsserver, lua-ls, etc) do support this as go-to-definition
