### ISSUE TITLE
Support for a custom Global Environment

### ISSUE THREAD

**Issue by ActualMasterOogway** [JohnnyMorganz/luau-lsp#623]
I think that'd be a nice feature to have

**Comment by JohnnyMorganz** [comment]
Can you expand? I do not know what you refer to

**Comment by ActualMasterOogway** [comment]
> Can you expand? I do not know what you refer to

I'm currently working in a custom luau environment. Lets say i have an "in-built" function called foo. When calling it, it doesnt error. But thing is the Language Server doesnt know that foo would actually exist and shoots out a type error: 
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/125769645/21000a1b-df87-4f8d-bee7-ad469e4beb91)
So, I'd like a way to basically let the Language Server know that foo is a valid global function.
I switched from [Roblox LSP](https://github.com/NightrainsRbx/RobloxLsp) to this and I really like it, but in Roblox LSP i could mark "foo" as a defined global: 
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/125769645/2194e2ea-bfc0-42be-b957-85c41d157fc2)

**Comment by JohnnyMorganz** [comment]
You can already do this by configuring custom definitions files with the setting `luau-lsp.types.definitionFiles`.

An example of such a file we use: https://github.com/JohnnyMorganz/luau-lsp/blob/main/scripts/globalTypes.d.luau

**Comment by ActualMasterOogway** [comment]
> You can already do this by configuring custom definitions files with the setting `luau-lsp.types.definitionFiles`.
> 
> An example of such a file we use: https://github.com/JohnnyMorganz/luau-lsp/blob/main/scripts/globalTypes.d.luau

Whooops, must have missed that my bad
