### ISSUE TITLE
Luau Diagnostics does not respect --!nocheck

### ISSUE THREAD

**Issue by sasial-dev** [JohnnyMorganz/luau-lsp#63]
I'm using a library and it has `--!nocheck` at the top of the file. Yet when I open it, luau still provides diagnostics.
<img width="1243" alt="Code-6aLP84sI" src="https://user-images.githubusercontent.com/44125644/177219716-9e637360-32ce-4156-b79e-d17a1d875aa1.png">

**Comment by JohnnyMorganz** [comment]
--!nocheck only prevents type errors. Those are lint diagnostics, which still show up.

You can configure diagnostics using a .luaurc file, which also allows you to disable them completely if you want to

**Comment by sasial-dev** [comment]
Hm, okay; I'm not sure if it's worth going into that much effort for a library, though!

**Comment by JohnnyMorganz** [comment]
Just to note, you can have multiple .luaurc files, and it will use the config closest to the current file.

Creating a new .luaurc file in the same directory as the library, with `"lints": { "*": false }` will disable them (or something along those lines, i don't remember the syntax exactly)
