### ISSUE TITLE
No autocompletion of uses of upvalues not at top level on lines created after sourcemap regeneration with project path using `..`

### ISSUE THREAD

**Issue by Ketasaja** [JohnnyMorganz/luau-lsp#645]
Reproduction for post-1.29.1 0ebfa54:
[luau-lsp_#645_reproduction.zip](https://github.com/user-attachments/files/15751246/luau-lsp_.645_reproduction.zip)
1. Open project in VS Code.
2. `aftman install`.
3. In `server/code/init.lua`, on line 2, start typing `autocomplete`.
![#645_working](https://github.com/JohnnyMorganz/luau-lsp/assets/153110145/8775dc73-e0ad-4627-b8a0-61c57d73749f)
4. Delete what you typed.
5. Insert at least two new lines within the function after line 2.
6. Start typing `autocomplete` again.
![#645_not_working](https://github.com/JohnnyMorganz/luau-lsp/assets/153110145/70802710-1e63-47a3-ab70-a2bc1f584153)
7. Delete what you typed.
8. Save the file.
9. Start typing `autocomplete` again.
![#645_working_again](https://github.com/JohnnyMorganz/luau-lsp/assets/153110145/4914b410-8ddd-4dce-a47f-93a3349a2f04)

`sourcemap.json`:
```json
{
  "emitLegacyScripts": false,
  "name": "Reproduction",
  "tree": {
    "$className": "DataModel",

    "ServerScriptService": {
      "server": {
        "$path": "directory/../server"
      }
    }
  }
}
```

**Comment by JohnnyMorganz** [comment]
The underlying cause seems to be the interesting sourcemap, where the filepath for `code` is stored as `"directory/../server\\code\\init.luau`. This causes us to fail to match the "real path" of this file with the path that VSCode understands (because we don't normalise it correctly). That is a bug, thanks for the report!

Curious why your project.json is configured to do it like this, seems odd.

**Comment by Ketasaja** [comment]
Thanks for the fix!

> Curious why your project.json is configured to do it like this, seems odd.

@JohnnyMorganz My project is a multi-place game, with root folders for code shared by all places, and for Wally packages since that can't be configured. Luau-LSP doesn't yet support multiple sourcemaps, so my workaround has been to run a command to replace root `default.project.json` with the `default.project.json` of the place folder I'm working on.
