### ISSUE TITLE
Inconsistent `Instance:FindFirstChild` types with absolute and relative paths

### ISSUE THREAD

**Issue by Ketasaja** [JohnnyMorganz/luau-lsp#647]
Since there can only be one service, it's surprising to me that `folder` and `folderAgain` don't have the same type. `luau-lsp.hover.strictDatamodelTypes` and `luau-lsp.diagnostics.strictDatamodelTypes` are `true`.
```lua
--!strict
local ReplicatedStorage = game:GetService("ReplicatedStorage")
-- `folder: Folder`
local folder = script.Parent.Parent:FindFirstChild("ReplicatedStorage"):FindFirstChild("Shared"):FindFirstChild("folder")
-- `folderAgain: Instance?`, `TypeError`
local folderAgain = ReplicatedStorage:FindFirstChild("Shared"):FindFirstChild("folder")
```
```json
{
  "name": "findfirstchild",
  "tree": {
    "$className": "DataModel",

    "ReplicatedStorage": {
      "Shared": {
        "$path": "src/shared"
      }
    },

    "ServerScriptService": {
      "Server": {
        "$path": "src/server"
      }
    }
  }
}
```
![luau-lsp-inconsistent-findfirstchild](https://github.com/JohnnyMorganz/luau-lsp/assets/153110145/c1aba29c-8c9d-4798-a99a-fd801825e3d9)

**Comment by JohnnyMorganz** [comment]
I think this should get fixed by f657718dcb1d709e82cb7202e242b34530cd7d6c. I will add a test case for this
