### ISSUE TITLE
Support Luau syntax highlighting in Markdown files

### ISSUE THREAD

**Issue by alexmccord** [JohnnyMorganz/luau-lsp#650]
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/11488393/54f2c1d7-87ac-4194-a1ca-121cac6f619e)

**Comment by JohnnyMorganz** [comment]
We won't be able to highlight the markdown preview due to vscode limitations (https://github.com/microsoft/vscode/issues/91279), but we can support highlighting the fenced codeblock in .md files
