### ISSUE TITLE
LuauLSP does not support LuaDoc

### ISSUE THREAD

**Issue by imkylecat** [JohnnyMorganz/luau-lsp#651]
Hello!

I'm working with a framework that makes use of ``shared()``, and in order to get intelisense to work you have to require modules like ``local Module = shared("Module") ---@module Module``. However unlike RobloxLSP, LuauLSP does not support LuaDoc so the whole ``---@module``, ``---class``, scheme does not work.

I really want to move to LuauLSP but this is the only thing holding me back.

**Comment by JohnnyMorganz** [comment]
Unfortunately we do not plan to support LuaDoc-style syntax to get types for the foreseeable future. You can use `shared("Module") :: typeof(require(path.to.Module))` for the equivalent in Luau.

**Comment by LastTalon** [comment]
I think this may be more related to EmmyLua rather than LuaDoc anyway, since that's what sumneko's Lua uses (the one RobloxLSP) is based on. I don't really think it's compatible with Luau.
