### ISSUE TITLE
Type definition file stopped working after 1.30.0

### ISSUE THREAD

**Issue by sweetboss12512** [JohnnyMorganz/luau-lsp#658]
I updated the extension and my definitions file fails to read
it works again when i revert to 1.29.1
settings.json:
```json
{
    "luau-lsp.sourcemap.enabled": false,
    "luau-lsp.platform.type": "roblox",
    "luau-lsp.types.definitionFiles": [
        "./build/pilot.d.lua"
    ],
}
```
definitions file:
[pilot.d.lua](https://github.com/user-attachments/files/15992633/pilot.d.txt)

**Comment by JohnnyMorganz** [comment]
pilot.d.lua files reference `Enum.Foo`, which is a mutated type definition. We started deferring our "definitions mutations" to post initialisation, meaning the pilot.d.luau files don't have access to the mutations, causing them to error. This is a bug, thanks for the report!
