### ISSUE TITLE
plugin should re-initialize when it detects a change to the rojo binary in the PATH

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/luau-lsp#67]
After starting up LSP and it complaining about my rojo sourcemap not working, I updated my foreman.toml to update rojo to 7.2.0 amd ran `foreman install`. It wasn't clear to me how to get the LSP to re-try with the new rojo beyond closing and re-opening the workspace.

It would be cool if it tracked the rojo binary (or symlink) update and re-ran sourcemap automatically.

**Comment by JohnnyMorganz** [comment]
Tracking this might be quite difficult, I'll take a look at it though

**Comment by JohnnyMorganz** [comment]
This is unfortunately too difficult to track right now.

If you run `foreman install`, it should however automatically use the newer rojo version, provided you haven't need to change your PATH variable (as refreshing that requires a VSCode restart)
