### ISSUE TITLE
Support Windows ARM for the VS Code Extension

### ISSUE THREAD

**Issue by dig1t** [JohnnyMorganz/luau-lsp#673]
Not able to install the VS Code LSP on a Windows ARM laptop.

I'm directed to this URL on the extension page: https://aka.ms/vscode-platform-specific-extensions

Screenshot:
![Screenshot](https://github.com/JohnnyMorganz/luau-lsp/assets/4343867/741ef910-7269-4ff3-8f33-6674699a09d8)

**Comment by howmanysmall** [comment]
any update on this? i'll be glad to help if you need the hardware to test

**Comment by dig1t** [comment]
I haven't been successful with getting compilation to cross compile an ARM64 executable on a normal windows machine, but publishing the extension to the vs marketplace has worked when running the release action in my repo fork.

The published extension also works with no issues on my windows arm64 laptop because if I'm not mistaken, the ARM64 machine runs the luau-lsp server under emulation. So I'm not sure if its worth the effort getting the action to compile an ARM64 executable unless the emulator isn't performing well.
