### ISSUE TITLE
How I cant fix game not being recognized?

### ISSUE THREAD

**Issue by Pymon02** [JohnnyMorganz/luau-lsp#674]
```luau
game.Players
```
```
TypeError: Key 'Players' not found in class 'DataModel'Luau[1002](https://luau-lang.org/typecheck)
```

**Comment by pavlo-tk** [comment]
Hi @ghost, how did you solve your problem?

I'm experiencing the same thing: the autocomplete doesn't suggest `Players` on `game`. In the same file, directly in Roblox Studio, the autocompletion works.

I'm using:
**VS Code**: 1.104.2
**Rojo VS Code plugin**: 2.1.2
**Rojo**: 7.5.1
**luau-lsp**: 1.54.0

**Comment by pavlo-tk** [comment]
For others who experience this issue, in my case, I solved it with the related plugin for Roblox Studio: [Luau Language Server Companion](https://create.roblox.com/store/asset/10913122509/Luau-Language-Server-Companion).

You need to install it in Roblox Studio and restart it. Then enable the plugin in the `luau-lsp` settings in VS Code. After that, I got the autocompletion that was missing before.

**Comment by Morfusee** [comment]
> For others who experience this issue, in my case, I solved it with the related plugin for Roblox Studio: [Luau Language Server Companion](https://create.roblox.com/store/asset/10913122509/Luau-Language-Server-Companion).
> 
> You need to install it in Roblox Studio and restart it. Then enable the plugin in the `luau-lsp` settings in VS Code. After that, I got the autocompletion that was missing before.

Thanks, this kinda fixed it!

To add on to this because I had a different workaround:

If _sourcemap.json_ got regenerated by luau-lsp: restart VSCode first, AND then restart the plugin on Roblox Studio.

For some reason, if the sourcemap got regenerated, the intellisense breaks. Been trying to fix this for a day now.

**Comment by JohnnyMorganz** [comment]
> If _sourcemap.json_ got regenerated by luau-lsp: restart VSCode first, AND then restart the plugin on Roblox Studio.
> 
> For some reason, if the sourcemap got regenerated, the intellisense breaks. Been trying to fix this for a day now.

Interesting, this seems like a bug. I'll open up a separate issue for this.
