### ISSUE TITLE
end keyword doesn't show up in intellisense when using a return statement

### ISSUE THREAD

**Issue by TumbleWede** [JohnnyMorganz/luau-lsp#677]
Sometimes the `end` keyword doesn't show up in intellisense when trying to end a code block.
This happens whenever i try to end a code block with a `return` statement, but ending a block with anything else works correctly.

https://github.com/JohnnyMorganz/luau-lsp/assets/71647082/6ab97cf8-0bc4-4c10-a887-3cafea517631

**Comment by JohnnyMorganz** [comment]
We get our end autocomplete suggestions from Luau. Does this also happen in Studio? Please file this issue upstream

**Comment by TumbleWede** [comment]
I just tested it and yes, Studio's built-in editor also has the exact same problem. I will file this issue to the Luau repository.
