### ISSUE TITLE
`Autocomplete End` should terminate the closest open block relative to the cursor

### ISSUE THREAD

**Issue by lolmanurfunny** [JohnnyMorganz/luau-lsp#680]
The lsp should terminate the closest open block relative to the cursor when a newline is added after a statement.

The current behavior of `luau-lsp.completion.autocompleteEnd` requires the cursor to be on the exact line that the block was opened. The problem with such behavior is that it does absolutely nothing for you when you're editing in the middle of or at the end of an open block, like during refactoring.

![Code_XW7OL9vlyg](https://github.com/user-attachments/assets/dea18156-60ba-42e8-b163-a667859a745d)

Related issue: #677

**Comment by JohnnyMorganz** [comment]
The reason we have this 1 line restriction is because otherwise if you have a larger file with 1 block unclosed early on in the file, we will introduce random 'end's continuously which can get annoying.

You'll see the same behaviour in Studio as well

**Comment by lolmanurfunny** [comment]
Yeah, I see. I figured it could get annoying... I'm not really sure that there's a realistic way to do this without it being unexpected in some cases.
