### ISSUE TITLE
A way to make all scripts have --!strict by default?

### ISSUE THREAD

**Issue by Pymon02** [JohnnyMorganz/luau-lsp#683]

**Comment by lolmanurfunny** [comment]
https://rfcs.luau-lang.org/config-luaurc.html

**Comment by JohnnyMorganz** [comment]
Will note it down to improve the docs in #635

**Comment by Pymon02** [comment]
Is there also a way to disable warnings it for one line in a file?

**Comment by JohnnyMorganz** [comment]
You can use a comment at the top of the file: https://github.com/JohnnyMorganz/luau-lsp/blob/main/scripts/globalTypes.PluginSecurity.d.luau
