### ISSUE TITLE
Separate auto-import ignores from `luau-lsp.ignoreGlobs`

### ISSUE THREAD

**Issue by lolmanurfunny** [JohnnyMorganz/luau-lsp#686]
I was trying to figure out why I wasn't able to auto-import my packages... eventually I realized that the `**/Packages/**` I had in my ignore globs was to blame.

The `luau-lsp.ignoreGlobs` setting currently influences auto-imports <sup>*yikes*</sup>, it should only influence diagnostics, as advertised (see image). Auto-imports should be given their own ignore globs. You shouldn't need to compute diagnostics for a file just to get it to show up in auto-imports.

![image](https://github.com/user-attachments/assets/c72f3a09-a4ee-4d74-b58d-98c4a6698192)

**Comment by JohnnyMorganz** [comment]
Agreed that the description doesn't make sense. However it is important we have an ignore in the first place, since we wouldn't want to auto import anything in `_Index`

Yes I think we should have a separate setting for auto import ignores
