### ISSUE TITLE
Support recursive find first child lookup for datamodel awareness

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/luau-lsp#689]
`game:FindFirstChild("Descendant", true)`

```luau
--[[
    Animator is not a direct child of TemplateR15, it is a descendant of it
    |_ TemplateR15
        |_ Humanoid
        |   |_ Animator
        |_ ...
]]
local template = workspace.TemplateR15
local animator = template:FindFirstChild("Animator") -- type is Instance?

local template = workspace.TemplateR15
local animator = template:FindFirstChild("Animator", true) -- type is Animator
```

**Comment by lolmanurfunny** [comment]
I think it's worth supporting `:FindFirstDescendant()` here as well for when it's eventually enabled.

**Comment by JohnnyMorganz** [comment]
Going to leave out FindFirstDescendant for now as there doesn't seem to be any value in supporting it just yet whilst it is still disabled. The docs seem to also indicate it won't be enabled any time soon. If it does get enabled, happy to support it
