### ISSUE TITLE
Enabling new type solver and `Hover` causes crash

### ISSUE THREAD

**Issue by Shamplify** [JohnnyMorganz/luau-lsp#692]
Enabling the `DebugLuauDeferredConstraintResolution` FFlag along with `luau-lsp.hover.enabled` causes crash upon hover.

https://github.com/user-attachments/assets/de177af1-fb49-4ba8-92c2-e7251f562aee

![image](https://github.com/user-attachments/assets/361592e9-97f8-4bb7-92ba-8b718b436426)

![image](https://github.com/user-attachments/assets/80307f7b-7aba-4bcb-8e7f-5cc4d251e90a)

**Comment by lolmanurfunny** [comment]
You're using an unreleased feature... don't expect the server to support it yet.
