### ISSUE TITLE
Autocomplete for dm-aware `:FindFirstChild()` calls break after 2nd child

### ISSUE THREAD

**Issue by lolmanurfunny** [JohnnyMorganz/luau-lsp#698]
The [test case](https://github.com/JohnnyMorganz/luau-lsp/commit/68b20f15cb752f6fb195a717944310d71d2dbacc#diff-602166f5fe34d589c31e9995737d7ebdfe220ef54a8e9673c712390258ed2748R407) for #685 didn't check for this.

![image](https://github.com/user-attachments/assets/0f67ce30-a10f-4c83-a669-b7447d6da223)
![image](https://github.com/user-attachments/assets/75f85f45-7875-4f68-bf33-b0e66fb4a3ec)

**Comment by JohnnyMorganz** [comment]
That test case should be the same as this one. I just added another test case and it also passes with the existing setup, so not sure what could've been different here.

In any case, maybe the fix for #699 will also fix this.

**Comment by JohnnyMorganz** [comment]
Can you confirm whether this got fixed in the recent update?

**Comment by lolmanurfunny** [comment]
Yeah, it was fixed:

![image](https://github.com/user-attachments/assets/d6c7957e-3812-4ffb-9687-c3b24d0a40f0)
