### ISSUE TITLE
1.32.0 is broken for Mac OS

### ISSUE THREAD

**Issue by ExtremeKiller145** [JohnnyMorganz/luau-lsp#710]
Version 1.32.0 does not work at least for MacOS 14.3.1, 

![image](https://github.com/user-attachments/assets/535e911e-d76e-4f4c-b4ff-14a5a8d5d1ba)

<img width="281" alt="Screenshot 2024-07-21 at 3 49 32 AM" src="https://github.com/user-attachments/assets/874600c3-be9a-4b75-89da-72d2255ef0d9">

The exact same error occurs for all the commands

**Comment by JohnnyMorganz** [comment]
This would happen if the server has not been activated yet. If you open a Luau file, what is the output in output window for Luau Language Server?

**Comment by ExtremeKiller145** [comment]
There's nothing here if this is what you meant:

<img width="1436" alt="Screenshot 2024-07-21 at 12 51 23 PM" src="https://github.com/user-attachments/assets/4137a297-bd18-4551-8eb0-0f64c3a28eb6">

**Comment by JohnnyMorganz** [comment]
Strange how it is not getting detected, but the luau file icons are changed. I'm not sure why your extension is not getting activated. There may be some relevant logs in one of the output channels.

Can you also check the developer console? It is possible the JavaScript portion of the extension errored out

**Comment by ExtremeKiller145** [comment]
The Icons are assigned by the Rojo extension, sorry about that.

<img width="420" alt="Screenshot 2024-07-21 at 11 28 18 PM" src="https://github.com/user-attachments/assets/357b3d8a-37cb-44d4-a459-856a87921e66">
<img width="1055" alt="Screenshot 2024-07-22 at 12 05 48 AM" src="https://github.com/user-attachments/assets/21641796-9235-4532-90d7-bee0f9b034e4">

Yeah it does seem to be the javascript.
If you need the full log, here it is:

[log.txt](https://github.com/user-attachments/files/16326427/log.txt)

**Comment by JohnnyMorganz** [comment]
What is your VSCode version? Also if you can go to the about VScode page can you check the version of Node.js?

**Comment by ExtremeKiller145** [comment]
Here it is:
<img width="279" alt="Screenshot 2024-07-22 at 4 49 10 PM" src="https://github.com/user-attachments/assets/a347b578-1b66-49b0-8ac0-5965ba4e1cb1">

**Comment by ExtremeKiller145** [comment]
Alright, so I fixed the issue. It was probably just outdated Node.js or outdated VS Code, so I updated and it fixed everything.

Here's the version now:
<img width="273" alt="Screenshot 2024-07-22 at 5 03 01 PM" src="https://github.com/user-attachments/assets/350ecfab-6921-4f9a-b3e1-b9674c5d6123">

As always, thanks for your help!

**Comment by JohnnyMorganz** [comment]
Yeah we need Node v18+. I'll look into increasing the minimum node requirement in the extension config
