### ISSUE TITLE
Hide inlay hints for `*error-type*`

### ISSUE THREAD

**Issue by jiwonz** [JohnnyMorganz/luau-lsp#711]
Please note. This is just a minor feature request for visual.

![image](https://github.com/user-attachments/assets/10cb222b-c120-4fe0-901a-d5b2169872aa)

It would look much cleaner if we could hide the inlay hints for `*error-type*`.

I think showing this up to me doesn't help much.

**Comment by lolmanurfunny** [comment]
I really hope this is configurable since I have all of the lsp's inlay hint options enabled so that I can use vscode's `"editor.inlayHints.enabled": "offUnlessPressed"` setting to quickly see information without perpetual suffering.
