### ISSUE TITLE
Performance issues VSC extension on version newer than 1.31.1

### ISSUE THREAD

**Issue by RuizuKun-Dev** [JohnnyMorganz/luau-lsp#720]
_I'm having issues with versions newer than 1.31.1, meaning version 1.31.1 has no issue but 1.32.0 and above do_

![image](https://github.com/user-attachments/assets/15460d47-ced0-4483-92a1-d1f948ee2eea)

Whenever i type something it doesn't update properly and sometimes even crashes

**Comment by RuizuKun-Dev** [comment]
> Please provide some reproduction steps since unforunately there is not much I can do to diagnose this otherwise

that's really tough because for me it always happens no matter what i do here's a video

https://github.com/user-attachments/assets/6b64ceeb-73c8-4cfd-871f-839af6221cc7

I'm on version 1.32.3

**Comment by JohnnyMorganz** [comment]
I plan on taking a deeper look at LSP performance issues. Can you generate a `trace.json` file and send it to me when you experience slowdowns? You will need to use a nightly build, but the steps are:

1) Download the latest nightly from https://github.com/JohnnyMorganz/luau-lsp/actions/workflows/nightly.yml for your platform. It will contain an archive for your platform. Download and extract, and you'll find a .vsix file inside. Install this into VSCode
2) Launch VSCode and enable the FFlag `DebugLuauTimeTracing`
3) Reload your window
4) Perform your work as normal
5) Run `Luau: Flush Time Tracing Events to tracing.json` command to write out a JSON file

This JSON file can be loaded into a visualiser such as chrome://tracing or Perfetto.

This will help to pinpoint the performance issues

**Comment by RuizuKun-Dev** [comment]
yep, i'll do that for you when i get the chance

**Comment by JohnnyMorganz** [comment]
Going to close this issue for now as there isn't anything actionable just yet.

If you hit the performance issue and you have a tracing.json as mentioned above, feel free to open a new issue about it
