### ISSUE TITLE
Autocomplete should only show keys when invoked within a typed table literal

### ISSUE THREAD

**Issue by lolmanurfunny** [JohnnyMorganz/luau-lsp#722]
![image](https://github.com/user-attachments/assets/ddd6bc44-e694-4c56-9ecc-f19e9a290005)

The above example makes it look tolerable, so here's it in an actual codebase (me pov):
![image](https://github.com/user-attachments/assets/d172e9b7-de8c-4483-9608-b2c853a1cb58)

**Comment by JohnnyMorganz** [comment]
This is a Luau issue, as we get autocomplete suggestions from there. You should file it upstream.

In this case though I imagine they might close it as a wontfix - it is still valid to put expressions in a table literal, hence expression completions show up
