### ISSUE TITLE
"Expected type table" error when accessing property with same name and type of union types

### ISSUE THREAD

**Issue by VictorGamerLOL** [JohnnyMorganz/luau-lsp#731]
If there is a value with a union type, and those 2 types share a property of the same name and type, trying to assign that property without refining the union type will throw an error in the LSP, whereas in the Roblox Studio script editor it does not say anything.

For example, having a value of type `TextLabel | TextBox` and trying to assign the `Text` property will cause the LSP to return "TypeError: Expected type table, got 'TextBox | TextLabel' instead".

![image](https://github.com/user-attachments/assets/dbcef232-d3e0-4cb9-8558-ba4196b76656)
![image](https://github.com/user-attachments/assets/5b80ce4c-a3ea-4f57-82c7-6631aae1cb50)

**Comment by JohnnyMorganz** [comment]
Type errors are Luau issues. Curious why it is not reported in Studio, but I assume it is because you got an `any` type in Studio

This is the issue upstream: https://github.com/luau-lang/luau/issues/533

**Comment by VictorGamerLOL** [comment]
When i declared the value i explicitly added the type annotations. Hovering over studio in fact does not say `any`
