### ISSUE TITLE
Relative requires are broken

### ISSUE THREAD

**Issue by Tazmondo** [JohnnyMorganz/luau-lsp#735]
Broken in version 1.32.2, works fine in 1.32.1.

Relative requires no longer work, raising a `TypeError: Unknown require: unsupported path`.
Modules don't show up in auto complete either, if starting from `script` instead of something like `ReplicatedStorage`.

Modules can still be required with absolute paths. There is also some interesting behaviour with Auto-Imports when the import mode is set to always relative.
![image](https://github.com/user-attachments/assets/f2d7c12a-03e6-40e2-8d8a-0abe039635c7)

**Comment by JohnnyMorganz** [comment]
I think it is the same issue affecting #734 too
