### ISSUE TITLE
git clone failure on luau directory

### ISSUE THREAD

**Issue by Yakend-bit** [JohnnyMorganz/luau-lsp#742]
Hello! issue:
When git cloning the repo, the luau folder is empty.

It needs to be deleted then you need to run git clone https://github.com/luau-lang/luau.git within the repo clone.

I don't know if this is a me issue, or a WSL Arch issue, but it is an issue that I took a while to figure out (I'm very nooby), but I thought it may be something to consider.

If this is expected behaviour, then no worries.

Thank you,
Yakend.

**Comment by Yakend-bit** [comment]
Doing git submodule update --init --recursive also works from within luau-lsp

**Comment by JohnnyMorganz** [comment]
Yes, it is a submodule, and you must initialise the submodule when you clone the repo
