### ISSUE TITLE
Load aliases from .luaurc

### ISSUE THREAD

**Issue by intervinn** [JohnnyMorganz/luau-lsp#759]
Is there be an option for lsp to load all aliases from `.luaurc`? For example, if I reuse a separate library with its own aliases, I'm gonna have to rewrite it all into my directory settings to fix the types.
![image](https://github.com/user-attachments/assets/d860faaf-2519-4e27-b1bd-7f7726ba4a66)

**Comment by JohnnyMorganz** [comment]
No, we do not support these yet. Unfortunately haven't had the time to work on this. Somewhat related is the issue #494 but surprised there is no existing issue for this yet.

**Comment by JohnnyMorganz** [comment]
Blocked on https://github.com/luau-lang/luau/issues/1417

**Comment by checkraisefold** [comment]
unblocked, working on this
