### ISSUE TITLE
`Instance:FindFirstChild()` and `Instance:FindFirstAncestor()` can't always be compared with `nil`

### ISSUE THREAD

**Issue by Qualadore** [JohnnyMorganz/luau-lsp#76]
```lua
--!strict
local model = Instance.new("Model")
assert(model:FindFirstChild("does_not_exist") ~= nil) -- This warns.
assert(workspace:FindFirstChild("does_not_exist") ~= nil) -- This is fine.
```
```
TypeError: Types Instance and nil cannot be compared with ~= because they do not have the same metatable
```

**Comment by Qualadore** [comment]
I've updated the issue to reflect the actual problem. I think `model ~= nil` should remain forbidden, even though Studio allows it.

**Comment by JohnnyMorganz** [comment]
Ah yeah, this is because FindFirstChild is currently typed as returning `Instance` instead of `Instance?`

I've been meaning to fix this, but not sure about potential impact. Especially in cases of find first child chains. What does studio type the return as?

**Comment by Qualadore** [comment]
It returns `Instance` in Studio. I like the idea of `Instance:FindFirstChild()` returning `Instance?`, even as someone who never uses `.` to access children. I think most people use `.` for most long chains.

**Comment by JohnnyMorganz** [comment]
Just an FYI about this currently, you can override the definitions used to support this, whilst you wait.
Its present at `%appdata%\Code\User\globalStorage\johnnymorganz.luau-lsp\globalTypes.d.lua` on Windows.
Note that the file will be overwritten whenever Roblox updates (which is weekly).

I'll look into the impact of changing it into an optional return

**Comment by JohnnyMorganz** [comment]
As an aside, #84 will add support to override the definitions file used completely, so that it won't get overwritten. Once environments are added, you can redefine the environment "roblox" with your own definitions file.
