### ISSUE TITLE
FuzzyEq method is missing from the CFrame data type

### ISSUE THREAD

**Issue by Daw588** [JohnnyMorganz/luau-lsp#768]
![RobloxStudioBeta_H7GPtyDw3N](https://github.com/user-attachments/assets/8dbf6586-580d-4b76-b120-63b59f812ee6)

This method exists and works in Roblox Studio, and it's [documented](https://create.roblox.com/docs/reference/engine/datatypes/CFrame#FuzzyEq) as well.

**Comment by checkraisefold** [comment]
closed by #803 @JohnnyMorganz
