### ISSUE TITLE
Diagnostics do not cleared for ignored files

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#77]
I would like Luau-LSP to copy Roblox Studio's "Type Inference Modes" behavior documented here: 
https://luau-lang.org/typecheck#type-inference-modes

This makes it easier to use other people's code that also uses these annotations without finding and changing ignore globs in vscode. I think this feature should be an optional setting in vscode to respect type inference modes annotation.

**Comment by JohnnyMorganz** [comment]
This should already be working.

Can you give an example of where this doesn't work?

**Comment by JohnnyMorganz** [comment]
Using the type inference mode comments does work for me when I open ProfileService.

I can confirm that ignore globs still don't work though - I will look into this more

**Comment by JohnnyMorganz** [comment]
Blocked by https://github.com/microsoft/vscode-languageserver-node/issues/1039
