### ISSUE TITLE
Add setting to prevent inline parameters being hidden when variable name is equal to the parameter name

### ISSUE THREAD

**Issue by Daimywil** [JohnnyMorganz/luau-lsp#779]
Currently, inline parameter names are automatically hidden when the variable name is equal to the parameter name. There should be a setting for this, as it can cause inconsistencies with showing inline parameter names.
![image](https://github.com/user-attachments/assets/a7976f65-f007-426e-8ec9-f1089c1cfd7f)

**Comment by JohnnyMorganz** [comment]
Should this setting only apply for parameter names, or also for variable / parameter types?

**Comment by Daimywil** [comment]
Could you clarify variable / parameter types?

**Comment by JohnnyMorganz** [comment]
![image](https://github.com/user-attachments/assets/7c55b25c-30b9-4612-9819-0353cc16faf9)

variable type: `MoneyInfo` (if `x` was renamed to `MoneyInfo`, the variable type would disappear since the variable name matches the type name)

ignore parameter types, we always show those

**Comment by Daimywil** [comment]
![image](https://github.com/user-attachments/assets/3480c2aa-1802-4210-9108-06070720fed7)
Parameter types also seem to be hidden if the name matches. I suggest applying this setting for both.
