### ISSUE TITLE
Add Disable FFLag Overrides setting

### ISSUE THREAD

**Issue by witchiestwitchery** [JohnnyMorganz/luau-lsp#801]
Currently theres no easy way to disable FFlag overrides you've made, making it annoying to ie disable the new solver because of how it doesn't work nicely with luau lsp right now. As the way I've been disabling my overrides is by abusing the adding a space to the end of the flag name bug, so they aren't enabled. This also gets especially annoying when you add in the 2 extra flags required to allow type functions

**Comment by JohnnyMorganz** [comment]
Can you not just comment them out of the settings.json file?

**Comment by witchiestwitchery** [comment]
> Can you not just comment them out of the settings.json file?

Oh, forgot about that existing...
