### ISSUE TITLE
Support Studio plugin to infer instance hierarchy

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#81]
Luau-lsp does not recognize required modules defined in rbxms. However, the instance of the ModuleScript is still recognized by luau-lsp. I expect requires of ModuleScripts defined in .rbxms to work with luau-lsp, but I get type errors instead, shown below. 

I have two reasons for keeping certain modules inside the .rbxl. The first reason is that I do not want to see several hundred modules from Roblox in my VSCode project. The second reason is to easily allow non-coders in my team create projects to edit particular module scripts without Rojo overwriting their work.

Here is an example project already setup with rbxm files: [lsp_bug.zip](https://github.com/JohnnyMorganz/luau-lsp/files/9166296/lsp_bug.zip) 
The included .rbxl shows that the code is valid and works with Rojo.

![image](https://user-images.githubusercontent.com/68730440/180403019-e4d7b842-1c93-4df0-8f04-5690cda4f1f1.png)

**Comment by JohnnyMorganz** [comment]
Unfortunately, because the script contents are embedded into the rbxm, this may be difficult for us to extract and use for typechecking, which is why you get an unknown require error.

I can look into rbxm support, but it might be quite challenging

**Comment by ArchLand64** [comment]
Is there anything that I can do to help speed up rbxm support? I can write a [remodel script](https://github.com/rojo-rbx/remodel) or a [CLI tool in C#](https://github.com/MaximumADHD/Roblox-File-Format) to get script contents from rbxms.

**Comment by JohnnyMorganz** [comment]
Your best bet is to unpack the rbxm with to create `.lua` scripts right now.

We could potentially add an "override" functionality so that you can keep the unpacked scripts in a gitignored folder and LSP uses the contents there, whilst the rbxm's remain in the main tree. Right now, you would have to replace the rbxm's with the unpacked scripts though

**Comment by ArchLand64** [comment]
Ok I can do that since I already use separate project.json files, but at this point, I think my batch and remodel scripts to support autocomplete are becoming an accessibility blocker for mass adoption by users unfamiliar with all these tools. So to make luau-lsp autocomplete setup/config easier, could you either use Roblox-LSP's existing [plugin for autocomplete](https://www.roblox.com/library/5969291145/Roblox-LSP-Plugin) or make your own? I think this would be good for minimizing fragmentation of how users set up their project for luau-lsp too.

**Comment by JohnnyMorganz** [comment]
Plugin would be reasonable, but it's a lot of work.

I will look into it

**Comment by JohnnyMorganz** [comment]
I was having a look at the plugin stuff. One thing I noticed, this gives instance autocomplete, but it won't solve requiring scripts?

We could potentially send over the wire all the script contents, but that sounds very expensive

**Comment by ArchLand64** [comment]
From what I see in Roblox-LSP's Roblox Studio plugin, it replicates instances as a data structure that looks like this: 
```js
type Instance = {
  Name: string,
  ClassName: string,
  Children: { Instance },
}
```

So yes, Roblox-LSP's Studio plugin won't solve requiring scripts, but you can easily write your own Studio plugin to support sending script contents. You can take a peek at Roblox LSP's Studio plugin code with BTRoblox (a chrome extension) or installing it in Studio and inserting its .rbxm file into a game. This would inform you about the quirks of Studio plugins and this type of task in particular.

A Studio plugin probably won't finish retrieving, serializing, and replicating instances for very large projects (>10 MB) in less than 16 milliseconds (to prevent visible lag spikes). But I believe you can amortize instance retrieval and serialization and it will be fast enough for your users (<3 seconds after they make game changes in Studio, VSCode should have an appropriate sourcemap.json) running on mid-tier hardware. I do not think replication (calling `HttpService:RequestAsync()`) will require amortization. If you need help with optimizing code for this, I would be happy to help.
