### ISSUE TITLE
Unkown Require When Using Fusion

### ISSUE THREAD

**Issue by Slimified** [JohnnyMorganz/luau-lsp#812]
I am attempting to use Fusion with Luau Language Server and Fusion, however, when putting Fusion in my ReplicatedStorage and attempting to require it through a script in Visual Studio Code, I get an error telling me that it is an unknown require, even though it works perfectly with syntax highlighting and autocompletion in Roblox Studio. Why is this? Fusion is a .rbxm file that I am putting in my shared directory in Rojo that is linked to my ReplicatedStorage.

**Comment by JohnnyMorganz** [comment]
Unfortunately, we do not support loading via `.rbxm` files, since Luau LSP does not come with a roblox model decoder

**Comment by JohnnyMorganz** [comment]
The only way I think we will ever support this is via the Studio Companion plugin (however, that will probably be in a long while).

Going to close this in favour of #747
