### ISSUE TITLE
Hover instance type refinement broken in Luau-LSP

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#814]
It looks like Instance type refinement broke in Luau-LSP, but hover types are still working correctly in Roblox Studio. Attached below is screenshot of Luau-LSP v1.34.0 in VSCode.

![image](https://github.com/user-attachments/assets/677538f5-a265-43fb-8973-a9d1955d7902)

Here is a screenshot of the expected hover type behavior in Roblox Studio's code editor.
![image](https://github.com/user-attachments/assets/6c51cddf-8e11-4d0a-a55c-a25ef059b7a8)

Here is my test code.
```luau
local obj: unknown = workspace
assert(typeof(obj) == "Instance")
local test: string = obj.Name
```

**Comment by JohnnyMorganz** [comment]
This seems to be broken since `Object` became the root class of `Instance`, causing this check to fail:

https://github.com/luau-lang/luau/blob/e6bf71871a6b9f601545dba8a42ce89c6069675c/Analysis/src/TypeInfer.cpp#L6404-L6405

We can add in a root tag here
