### ISSUE TITLE
False type errors with circular types

### ISSUE THREAD

**Issue by ArchLand64** [JohnnyMorganz/luau-lsp#82]
Luau-lsp reports a type error for the code below, when Roblox Studio reports no errors.
```lua
--!strict

type Foo = {
	LinkName: string,
	Pointer: Bar?
}

type Bar = {
	LinkName: string,
	Pointer: Foo,
}

local _test: Bar = {
	LinkName = "Test1",
	Pointer = {
		LinkName = "Test2",
	}
}
```

Here is a screenshot of the type error that I am seeing.
![image](https://user-images.githubusercontent.com/68730440/180417067-8d50ef78-65ef-48a3-9df8-d360b6883046.png)

**Comment by JohnnyMorganz** [comment]
Required a Luau update. Fixed in https://github.com/JohnnyMorganz/luau-lsp/commit/bbd9c53a3521df75f564eb684c1773f91c8c1648
