### ISSUE TITLE
Support for Instance.new() in table values

### ISSUE THREAD

**Issue by danaetroupe** [JohnnyMorganz/luau-lsp#836]
![image](https://github.com/user-attachments/assets/4b81f12d-da6f-49b3-a0a5-94b2b43cdeb1)
Luau-lsp currently does not update type based on instance.new type. Type is given in the string. When used in a new variable it works, but not when updating a table value.

**Comment by danaetroupe** [comment]
![image](https://github.com/user-attachments/assets/985b91a5-e450-4240-9acb-498db421ca27)
I think in general when values are added to a table key, the program does not take that into consideration.

**Comment by JohnnyMorganz** [comment]
Can you show the error you are experiencing, and create a minimal example that I can test with?

But, this is looking like it might be a Luau issue. Do you also experience this in Roblox Studio? If so, I would recommend you report it to the Luau team directly

**Comment by danaetroupe** [comment]
Checked in Roblox Studio, and am getting a TypeError there as well. Will raise the issue with the Luau team, thanks for your help. 
`lua
--!strict

type TestObj = {
	model : Model?
}

local object : TestObj = {
	model = nil
}

object.model = Instance.new("Model")
object.model.Parent = workspace`
Included the code if you're interested in taking a look.
