### ISSUE TITLE
Enum types is Never in elif statements.

### ISSUE THREAD

**Issue by Evangelicious** [JohnnyMorganz/luau-lsp#838]
Unsure if this apply to other Enums or if it's a KeyCode thing. Could also be linked to another non-issue where intellisense stop suggesting after a few table scope despite type being correctly checked?

![Capture](https://github.com/user-attachments/assets/ac4495c9-d6b1-4be3-983c-c4d78e05a82a)

```luau
local UserInputService = game:GetService("UserInputService")
UserInputService.InputBegan:Connect(function(input)
    if input.KeyCode == Enum.KeyCode.A then
        print("The first Enum works.")
    elseif input.KeyCode == Enum.KeyCode.Q then
        print("Enum is never </3")
    end
end)
```

**Comment by JohnnyMorganz** [comment]
I can reproduce this in Roblox Studio, so this is a Luau bug. I would recommend reporting to them

**Comment by JohnnyMorganz** [comment]
Closing this issue. If it ends up being a luau-lsp specific problem, not Luau / Roblox, then feel free to reopen
