### ISSUE TITLE
Register a JSON schema for `.luaurc` files

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/luau-lsp#842]

**Comment by ernisto** [comment]
where can i put the json schema ? i have been made a schema
![image](https://github.com/user-attachments/assets/cbe142bc-9313-4a67-b9c1-c91968b8232e)

**Comment by JohnnyMorganz** [comment]
Nice, thanks! You can submit a PR to add it into `editors/code/schemas`, then register it in `package.json` like as documented at https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation
