### ISSUE TITLE
Path2DControlPoint.new falsely errors

### ISSUE THREAD

**Issue by ActualMasterOogway** [JohnnyMorganz/luau-lsp#847]
![image](https://github.com/user-attachments/assets/3ee4b42a-874e-4c67-a5da-621e65caf1b3)
`local ControlPoint = Path2DControlPoint.new(UDim2.new(0, 0, 0, 0))`
TypeError: Type 'UDim2' from '@ roblox' could not be converted into 'UDim2' from '@ roblox' Luau([1000](https://luau-lang.org/typecheck))

Should I report this issue to the Luau Repo or is it an issue in Luau LSP?

**Comment by notpoiu** [comment]
<img width="782" alt="image" src="https://github.com/user-attachments/assets/2ef50257-3b46-4ce5-b44a-294617615b74">

I also got a issue like this:
```luau
function Script.Functions.IsKeyDownWrapper(key: Enum.KeyCode)
    return shared.UserInputService:IsKeyDown(key)
end
```

**Comment by JohnnyMorganz** [comment]
This would be an LSP issue, however I cannot reproduce either example. Can you send a minimal example?

![image](https://github.com/user-attachments/assets/2824a1f6-0775-4d2b-8a37-8a6491d7b7ea)

**Comment by ActualMasterOogway** [comment]
> This would be an LSP issue, however I cannot reproduce either example. Can you send a minimal example?
> 
> ![image](https://private-user-images.githubusercontent.com/19635171/391239836-2824a1f6-0775-4d2b-8a37-8a6491d7b7ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNjY0MzYsIm5iZiI6MTczMzA2NjEzNiwicGF0aCI6Ii8xOTYzNTE3MS8zOTEyMzk4MzYtMjgyNGExZjYtMDc3NS00ZDJiLThhMzctOGE2NDkxZDdiN2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE1MTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYzQxMjg4ZjRhODc0Y2U4MzY1ODM3MTRmZTYwZmMxZjY0OWMwYzdiMjNiZTEzODQxNjExZWZmOGE0NDdkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KFxVnDM_KDK7ibNRC1t5EjVste5ajQyCsStgzna8vUY)

It looks like the latest update has fixed this Issue.
