### ISSUE TITLE
autocomplete for relative string require is wrong

### ISSUE THREAD

**Issue by FlowGnarly** [JohnnyMorganz/luau-lsp#851]
After switching to [1.36.0](https://github.com/JohnnyMorganz/luau-lsp/releases/tag/1.36.0) I no longer get autocomplete when I use the current directory prefix (`./`) in the require function

![image](https://github.com/user-attachments/assets/fd43a4a7-41af-4907-bf88-9752bd24dd2e)

however autocomplete for aliases and the parent directory prefix (`../`) works as expected.

![image](https://github.com/user-attachments/assets/165d63d2-25de-44fd-bb7c-c3db793c43a6)

![image](https://github.com/user-attachments/assets/74aecbb4-6f40-49c7-8020-a466173eda72)

![image](https://github.com/user-attachments/assets/7fd1aff1-65aa-4a8d-a6f4-2660798b7d45)

I expect to get the same autocomplete from image 2 and 4 in image 1, did I miss something from any luau rfc?

**Comment by FlowGnarly** [comment]
looks like the autocomplete for relative string require is completely wrong
`./` doesnt work at all
`../` gets the current directory (its supposed to get the parent directory)
`../../` gets the parent directory

**Comment by JohnnyMorganz** [comment]
I also noticed that autocomplete of directory aliases broke too. I am not getting any autocomplete for `@lune/`
