### ISSUE TITLE
Wrapping dynamic property access in pcall() does not suppress TypeError

### ISSUE THREAD

**Issue by Omgeta** [JohnnyMorganz/luau-lsp#869]
In the code excerpt below, I can't suppress the error `TypeError: Attempting a dynamic property access on type 'Instance' is unsafe and may cause exceptions at runtime` with a pcall()

```lua
local object = Instance.new(className) -- className is dynamic
local success, err = pcall(function()
	object[property] = value
end)
```

**Comment by JohnnyMorganz** [comment]
This isn't a runtime error, it is a static lint.

You can solve this by doing `(object :: any)[property] = value`, you don't need the pcall

**Comment by Omgeta** [comment]
Ah I see. Thank you for the help
