### ISSUE TITLE
Detect early exit to prevent "TypeError: Value of type '<Type>?' could be nil (1029)"

### ISSUE THREAD

**Issue by mikejohnstn** [JohnnyMorganz/luau-lsp#89]
The nil checker doesn't seem smart enough to detect if you've early exited from a function with something like this:
```
if myOptionalVar == nil then
   return
end

print(myOptionalVar)  -- Gives error 1029
```

It'd be great to fix this! Happens to me a lot. In the meantime, is there a way to selectively disable this error?

**Comment by JohnnyMorganz** [comment]
This is a Luau issue:
https://github.com/Roblox/luau/issues/356

As mentioned there, your two options right now are to move your code onto the else block, or use an assert statement

**Comment by mikejohnstn** [comment]
Thanks for the link.

In the meantime is there a way to ask luau-lsp / VS Code to suppress certain warning / error codes? I might prefer that for now instead of adding lots of asserts.

**Comment by JohnnyMorganz** [comment]
You can granularly configure lints, but unfortunately I don't think you can do the same for type errors. (configuration is done by luau in .luaurc files https://github.com/Roblox/luau/blob/master/rfcs/config-luaurc.md)

I can look at potentially doing a LSP specific config for this

**Comment by JohnnyMorganz** [comment]
Fixes for this issue have been pushed upstream :)

It should be available in the next LSP release in the next few days.

It will currently require enabling the FFlag `LuauTinyControlFlowAnalysis`
