### ISSUE TITLE
Allow a Type Checking Only mode.

### ISSUE THREAD

**Issue by ryan-pate** [JohnnyMorganz/luau-lsp#92]
Luau-LSP's type checker works great, but i feel like the IntelliSense isn't quite as good (for me) as Roblox LSP in its current state. My solution is to add a Type-Check-Only flag in the settings to allow developers to use Roblox LSP for IntelliSense, and Luau LSP for Type Warnings.

**Comment by JohnnyMorganz** [comment]
You can now granularly disable certain LSP features if you wish, using the following settings:
- `luau-lsp.completion.enabled`
- `luau-lsp.hover.enabled`
- `luau-lsp.signatureHelp.enabled`
