### ISSUE TITLE
UTF-8 error within globalTypes.d.lua causes invalid typechecking

### ISSUE THREAD

**Issue by SnowdustDev** [JohnnyMorganz/luau-lsp#94]
Freshly installed this extension with no conflicting extensions (eg. RobloxLSP), getting a strange error that causes substantial typechecking inaccuracy and general bugs

`Failed to read definitions file c:/Users/Snowdust/AppData/Roaming/Code/User/globalStorage/johnnymorganz.luau-lsp/globalTypes.d.lua. Extended types will not be provided`

![image](https://user-images.githubusercontent.com/81551621/183313909-a842ac4f-4998-4e09-903a-e33fe1ec4466.png)

`SyntaxError: Expected identifier when parsing expression, got invalid UTF-8 sequence`

![image](https://user-images.githubusercontent.com/81551621/183313908-ee3edb91-f262-47a1-9ff2-7585fb2affb6.png)

**Comment by SnowdustDev** [comment]
[globalTypes.d.lua.txt](https://github.com/JohnnyMorganz/luau-lsp/files/9277757/globalTypes.d.lua.txt)
Forgot to attach the file. Renamed to .txt since github doesn't like the .lua extension

**Comment by JohnnyMorganz** [comment]
Ah, I regenerated the types file, but I used PowerShell which inserts a BOM that Luau is not happy with, whoops.

It can be regenerated by running `python dumpRobloxTypes.py > globalTypes.d.Lua`.
I can't update it right now, but I'll do it ASAP - most likely tomorrow though

**Comment by SnowdustDev** [comment]
Thank you! Can confirm manually running `dumpRobloxTypes.py` fixes it

**Comment by JohnnyMorganz** [comment]
Should hopefully be fixed now, let me know if it's still an issue.

You can manually redownload the file by running the "update API" command
