### ISSUE TITLE
Hide problems when file is removed unconventionally

### ISSUE THREAD

**Issue by Qualadore** [JohnnyMorganz/luau-lsp#96]
With the VS Code extension, if a Luau file has a warning and I delete it normally, the problem disappears from the Problems widget. But if I instead use `git stash`, the file is removed but the warning remains in Problems until I reopen VS Code.

**Comment by JohnnyMorganz** [comment]
This is an upstream bug: https://github.com/microsoft/vscode-languageserver-node/issues/1052
